window.MANDAYRIN_VOCAB = {
  noun: [
    // First steps — days 1–120
    ["人", "rén", "person"], ["家", "jiā", "home; family"], ["水", "shuǐ", "water"],
    ["饭", "fàn", "meal; rice"], ["书", "shū", "book"], ["朋友", "péngyou", "friend"],
    ["老师", "lǎoshī", "teacher"], ["学生", "xuésheng", "student"], ["猫", "māo", "cat"],
    ["狗", "gǒu", "dog"], ["学校", "xuéxiào", "school"], ["时间", "shíjiān", "time"],
    ["妈妈", "māma", "mom"], ["爸爸", "bàba", "dad"], ["孩子", "háizi", "child"],
    ["名字", "míngzi", "name"], ["中国", "Zhōngguó", "China"], ["美国", "Měiguó", "United States"],
    ["今天", "jīntiān", "today"], ["明天", "míngtiān", "tomorrow"], ["昨天", "zuótiān", "yesterday"],
    ["早上", "zǎoshang", "morning"], ["晚上", "wǎnshang", "evening"], ["钱", "qián", "money"],
    ["手机", "shǒujī", "phone"], ["电脑", "diànnǎo", "computer"], ["桌子", "zhuōzi", "table"],
    ["椅子", "yǐzi", "chair"], ["门", "mén", "door"], ["车", "chē", "car; vehicle"],
    ["路", "lù", "road"], ["店", "diàn", "shop"], ["医院", "yīyuàn", "hospital"],
    ["医生", "yīshēng", "doctor"], ["苹果", "píngguǒ", "apple"], ["茶", "chá", "tea"],
    ["咖啡", "kāfēi", "coffee"], ["米饭", "mǐfàn", "cooked rice"], ["衣服", "yīfu", "clothes"],
    ["鞋", "xié", "shoes"],

    // Everyday basics — days 121–240
    ["房间", "fángjiān", "room"], ["厨房", "chúfáng", "kitchen"], ["洗手间", "xǐshǒujiān", "restroom"],
    ["床", "chuáng", "bed"], ["窗户", "chuānghu", "window"], ["电视", "diànshì", "television"],
    ["杯子", "bēizi", "cup"], ["盘子", "pánzi", "plate"], ["筷子", "kuàizi", "chopsticks"],
    ["包", "bāo", "bag"], ["票", "piào", "ticket"], ["地图", "dìtú", "map"],
    ["公园", "gōngyuán", "park"], ["银行", "yínháng", "bank"], ["超市", "chāoshì", "supermarket"],
    ["餐厅", "cāntīng", "restaurant"], ["公司", "gōngsī", "company"], ["工作", "gōngzuò", "job; work"],
    ["公交车", "gōngjiāochē", "bus"], ["地铁", "dìtiě", "subway"], ["火车", "huǒchē", "train"],
    ["飞机", "fēijī", "airplane"], ["机场", "jīchǎng", "airport"], ["城市", "chéngshì", "city"],
    ["国家", "guójiā", "country"], ["天气", "tiānqì", "weather"], ["雨", "yǔ", "rain"],
    ["雪", "xuě", "snow"], ["风", "fēng", "wind"], ["太阳", "tàiyáng", "sun"],
    ["月亮", "yuèliang", "moon"], ["山", "shān", "mountain"], ["河", "hé", "river"],
    ["海", "hǎi", "sea"], ["花", "huā", "flower"], ["树", "shù", "tree"],
    ["鸟", "niǎo", "bird"], ["鱼", "yú", "fish"], ["牛奶", "niúnǎi", "milk"],
    ["面包", "miànbāo", "bread"],

    // Growing basics — days 241–365
    ["鸡蛋", "jīdàn", "egg"], ["面条", "miàntiáo", "noodles"], ["水果", "shuǐguǒ", "fruit"],
    ["蔬菜", "shūcài", "vegetables"], ["早餐", "zǎocān", "breakfast"], ["午饭", "wǔfàn", "lunch"],
    ["晚饭", "wǎnfàn", "dinner"], ["星期", "xīngqī", "week"], ["周末", "zhōumò", "weekend"],
    ["生日", "shēngrì", "birthday"], ["问题", "wèntí", "question"], ["答案", "dá’àn", "answer"],
    ["语言", "yǔyán", "language"], ["汉语", "Hànyǔ", "Mandarin Chinese"], ["英语", "Yīngyǔ", "English"],
    ["音乐", "yīnyuè", "music"], ["电影", "diànyǐng", "movie"], ["照片", "zhàopiàn", "photo"],
    ["颜色", "yánsè", "color"], ["声音", "shēngyīn", "sound; voice"], ["身体", "shēntǐ", "body"],
    ["头", "tóu", "head"], ["手", "shǒu", "hand"], ["眼睛", "yǎnjing", "eyes"],
    ["嘴", "zuǐ", "mouth"], ["心", "xīn", "heart"], ["家庭", "jiātíng", "family; household"],
    ["叔叔", "shūshu", "uncle"], ["阿姨", "āyí", "aunt"], ["同事", "tóngshì", "coworker"],
    ["邻居", "línjū", "neighbor"], ["经理", "jīnglǐ", "manager"], ["服务员", "fúwùyuán", "server"],
    ["厨师", "chúshī", "cook; chef"], ["事情", "shìqing", "matter; thing"], ["地方", "dìfang", "place"],
    ["机会", "jīhuì", "opportunity"], ["习惯", "xíguàn", "habit"], ["计划", "jìhuà", "plan"],
    ["故事", "gùshi", "story"]
  ],

  verb: [
    // First steps — days 1–120
    ["是", "shì", "to be"], ["有", "yǒu", "to have"], ["去", "qù", "to go"],
    ["来", "lái", "to come"], ["吃", "chī", "to eat"], ["喝", "hē", "to drink"],
    ["看", "kàn", "to look; to watch"], ["听", "tīng", "to listen"], ["说", "shuō", "to speak"],
    ["读", "dú", "to read"], ["写", "xiě", "to write"], ["喜欢", "xǐhuan", "to like"],
    ["爱", "ài", "to love"], ["要", "yào", "to want; to need"], ["想", "xiǎng", "to think; to want"],
    ["知道", "zhīdào", "to know"], ["认识", "rènshi", "to know; to meet"], ["叫", "jiào", "to be called"],
    ["给", "gěi", "to give"], ["买", "mǎi", "to buy"], ["卖", "mài", "to sell"],
    ["做", "zuò", "to do; to make"], ["用", "yòng", "to use"], ["开", "kāi", "to open; to drive"],
    ["关", "guān", "to close"], ["坐", "zuò", "to sit; to ride"], ["站", "zhàn", "to stand"],
    ["走", "zǒu", "to walk; to leave"], ["跑", "pǎo", "to run"], ["睡", "shuì", "to sleep"],
    ["起床", "qǐchuáng", "to get up"], ["回", "huí", "to return"], ["找", "zhǎo", "to look for"],
    ["问", "wèn", "to ask"], ["回答", "huídá", "to answer"], ["学", "xué", "to learn"],
    ["教", "jiāo", "to teach"], ["工作", "gōngzuò", "to work"], ["等", "děng", "to wait"],
    ["帮助", "bāngzhù", "to help"],

    // Everyday basics — days 121–240
    ["穿", "chuān", "to wear"], ["脱", "tuō", "to take off"], ["洗", "xǐ", "to wash"],
    ["洗澡", "xǐzǎo", "to bathe"], ["刷牙", "shuāyá", "to brush teeth"], ["做饭", "zuòfàn", "to cook"],
    ["点", "diǎn", "to order; to point"], ["付", "fù", "to pay"], ["打电话", "dǎ diànhuà", "to make a phone call"],
    ["发", "fā", "to send"], ["收", "shōu", "to receive"], ["拿", "ná", "to take; to hold"],
    ["放", "fàng", "to put"], ["带", "dài", "to bring; to carry"], ["进", "jìn", "to enter"],
    ["出", "chū", "to exit"], ["上", "shàng", "to go up; to attend"], ["下", "xià", "to go down; to get off"],
    ["到", "dào", "to arrive"], ["离开", "líkāi", "to leave"], ["开始", "kāishǐ", "to begin"],
    ["结束", "jiéshù", "to finish"], ["休息", "xiūxi", "to rest"], ["玩", "wán", "to play"],
    ["唱", "chàng", "to sing"], ["跳", "tiào", "to jump; to dance"], ["笑", "xiào", "to smile; to laugh"],
    ["哭", "kū", "to cry"], ["住", "zhù", "to live"], ["旅行", "lǚxíng", "to travel"],
    ["游泳", "yóuyǒng", "to swim"], ["运动", "yùndòng", "to exercise"], ["见", "jiàn", "to see; to meet"],
    ["觉得", "juéde", "to feel; to think"], ["记得", "jìde", "to remember"], ["忘记", "wàngjì", "to forget"],
    ["懂", "dǒng", "to understand"], ["练习", "liànxí", "to practice"], ["准备", "zhǔnbèi", "to prepare"],
    ["决定", "juédìng", "to decide"],

    // Growing basics — days 241–365
    ["需要", "xūyào", "to need"], ["希望", "xīwàng", "to hope"], ["选择", "xuǎnzé", "to choose"],
    ["改变", "gǎibiàn", "to change"], ["发现", "fāxiàn", "to discover"], ["介绍", "jièshào", "to introduce"],
    ["解释", "jiěshì", "to explain"], ["比较", "bǐjiào", "to compare"], ["参加", "cānjiā", "to participate"],
    ["计划", "jìhuà", "to plan"], ["安排", "ānpái", "to arrange"], ["完成", "wánchéng", "to complete"],
    ["检查", "jiǎnchá", "to check"], ["修理", "xiūlǐ", "to repair"], ["打扫", "dǎsǎo", "to clean"],
    ["搬家", "bānjiā", "to move home"], ["借", "jiè", "to borrow"], ["还", "huán", "to return something"],
    ["送", "sòng", "to give; to deliver"], ["接", "jiē", "to receive; to pick up"], ["换", "huàn", "to change; to exchange"],
    ["试", "shì", "to try"], ["订", "dìng", "to reserve; to order"], ["切", "qiē", "to cut"],
    ["炒", "chǎo", "to stir-fry"], ["煮", "zhǔ", "to boil; to cook"], ["烧", "shāo", "to burn; to cook"],
    ["开会", "kāihuì", "to have a meeting"], ["上班", "shàngbān", "to go to work"], ["下班", "xiàbān", "to finish work"],
    ["请", "qǐng", "to invite; please"], ["告诉", "gàosu", "to tell"], ["相信", "xiāngxìn", "to believe"],
    ["担心", "dānxīn", "to worry"], ["同意", "tóngyì", "to agree"], ["反对", "fǎnduì", "to oppose"],
    ["保护", "bǎohù", "to protect"], ["照顾", "zhàogù", "to take care of"], ["分享", "fēnxiǎng", "to share"],
    ["复习", "fùxí", "to review"]
  ],

  adjective: [
    // First steps — days 1–120
    ["好", "hǎo", "good"], ["大", "dà", "big"], ["小", "xiǎo", "small"],
    ["多", "duō", "many; much"], ["少", "shǎo", "few; little"], ["新", "xīn", "new"],
    ["老", "lǎo", "old"], ["快", "kuài", "fast"], ["慢", "màn", "slow"],
    ["高兴", "gāoxìng", "happy"], ["漂亮", "piàoliang", "pretty"], ["简单", "jiǎndān", "simple"],
    ["高", "gāo", "tall; high"], ["矮", "ǎi", "short; low"], ["长", "cháng", "long"],
    ["短", "duǎn", "short"], ["热", "rè", "hot"], ["冷", "lěng", "cold"],
    ["忙", "máng", "busy"], ["累", "lèi", "tired"], ["饿", "è", "hungry"],
    ["渴", "kě", "thirsty"], ["贵", "guì", "expensive"], ["便宜", "piányi", "inexpensive"],
    ["对", "duì", "correct"], ["错", "cuò", "wrong"], ["早", "zǎo", "early"],
    ["晚", "wǎn", "late"], ["远", "yuǎn", "far"], ["近", "jìn", "near"],
    ["红", "hóng", "red"], ["蓝", "lán", "blue"], ["白", "bái", "white"],
    ["黑", "hēi", "black"], ["甜", "tián", "sweet"], ["辣", "là", "spicy"],
    ["咸", "xián", "salty"], ["好吃", "hǎochī", "tasty"], ["好看", "hǎokàn", "good-looking"],
    ["可爱", "kě’ài", "cute"],

    // Everyday basics — days 121–240
    ["干净", "gānjìng", "clean"], ["脏", "zāng", "dirty"], ["安静", "ānjìng", "quiet"],
    ["吵", "chǎo", "noisy"], ["容易", "róngyì", "easy"], ["难", "nán", "difficult"],
    ["重要", "zhòngyào", "important"], ["有趣", "yǒuqù", "interesting"], ["无聊", "wúliáo", "boring"],
    ["开心", "kāixīn", "happy"], ["难过", "nánguò", "sad"], ["生气", "shēngqì", "angry"],
    ["害怕", "hàipà", "afraid"], ["紧张", "jǐnzhāng", "nervous"], ["舒服", "shūfu", "comfortable"],
    ["难受", "nánshòu", "uncomfortable"], ["健康", "jiànkāng", "healthy"], ["强壮", "qiángzhuàng", "strong; healthy"],
    ["年轻", "niánqīng", "young"], ["旧", "jiù", "old; used"], ["好玩", "hǎowán", "fun"],
    ["有名", "yǒumíng", "famous"], ["特别", "tèbié", "special"], ["一样", "yíyàng", "the same"],
    ["不同", "bùtóng", "different"], ["满", "mǎn", "full"], ["空", "kōng", "empty"],
    ["亮", "liàng", "bright"], ["暗", "àn", "dark"], ["轻", "qīng", "light"],
    ["重", "zhòng", "heavy"], ["厚", "hòu", "thick"], ["薄", "báo", "thin"],
    ["硬", "yìng", "hard"], ["软", "ruǎn", "soft"], ["干", "gān", "dry"],
    ["湿", "shī", "wet"], ["清楚", "qīngchu", "clear"], ["模糊", "móhu", "blurry"],
    ["安全", "ānquán", "safe"],

    // Growing basics — days 241–365
    ["认真", "rènzhēn", "serious; conscientious"], ["小心", "xiǎoxīn", "careful"], ["聪明", "cōngming", "smart"],
    ["友好", "yǒuhǎo", "friendly"], ["礼貌", "lǐmào", "polite"], ["诚实", "chéngshí", "honest"],
    ["勇敢", "yǒnggǎn", "brave"], ["耐心", "nàixīn", "patient"], ["热情", "rèqíng", "enthusiastic"],
    ["亲切", "qīnqiè", "kind; warm"], ["丰富", "fēngfù", "rich; abundant"], ["新鲜", "xīnxiān", "fresh"],
    ["方便", "fāngbiàn", "convenient"], ["麻烦", "máfan", "troublesome"], ["正确", "zhèngquè", "correct"],
    ["明白", "míngbai", "clear; understood"], ["整齐", "zhěngqí", "tidy"], ["美丽", "měilì", "beautiful"],
    ["普通", "pǔtōng", "ordinary"], ["流行", "liúxíng", "popular"], ["合适", "héshì", "suitable"],
    ["可能", "kěnéng", "possible"], ["一定", "yídìng", "certain"], ["相同", "xiāngtóng", "the same"],
    ["相反", "xiāngfǎn", "opposite"], ["直接", "zhíjiē", "direct"], ["自然", "zìrán", "natural"],
    ["复杂", "fùzá", "complex"], ["成功", "chénggōng", "successful"], ["幸运", "xìngyùn", "lucky"],
    ["奇怪", "qíguài", "strange"], ["可惜", "kěxī", "unfortunate"], ["可怕", "kěpà", "scary"],
    ["热闹", "rènao", "lively"], ["传统", "chuántǒng", "traditional"], ["现代", "xiàndài", "modern"],
    ["自由", "zìyóu", "free"], ["主要", "zhǔyào", "main; primary"], ["必要", "bìyào", "necessary"],
    ["满意", "mǎnyì", "satisfied"]
  ]
};
