"""The HSK 1 word budget that Newbie stories are written inside.

Du Chinese Newbie stories advertise "a vocabulary of 150 characters", which is
the HSK 1 (2.0) list below. Keeping it here rather than in a prompt means the
model is handed the exact budget every time instead of being asked to remember
what HSK 1 contains, and the same list can be shown in the workshop UI.
"""

from __future__ import annotations


# (simplified, pinyin, english). Ordered roughly by pinyin, as in the official
# HSK 1 list.
HSK1_WORDS: tuple[tuple[str, str, str], ...] = (
    ("爱", "ài", "to love"),
    ("八", "bā", "eight"),
    ("爸爸", "bàba", "dad"),
    ("杯子", "bēizi", "cup"),
    ("北京", "Běijīng", "Beijing"),
    ("本", "běn", "measure word for books"),
    ("不客气", "bú kèqi", "you're welcome"),
    ("不", "bù", "not; no"),
    ("菜", "cài", "dish; vegetable"),
    ("茶", "chá", "tea"),
    ("吃", "chī", "to eat"),
    ("出租车", "chūzūchē", "taxi"),
    ("打电话", "dǎ diànhuà", "to make a phone call"),
    ("大", "dà", "big"),
    ("的", "de", "possessive particle"),
    ("点", "diǎn", "o'clock; a little"),
    ("电脑", "diànnǎo", "computer"),
    ("电视", "diànshì", "television"),
    ("电影", "diànyǐng", "film"),
    ("东西", "dōngxi", "thing"),
    ("都", "dōu", "all; both"),
    ("读", "dú", "to read"),
    ("对不起", "duìbuqǐ", "sorry"),
    ("多", "duō", "many; much"),
    ("多少", "duōshao", "how many; how much"),
    ("儿子", "érzi", "son"),
    ("二", "èr", "two"),
    ("饭店", "fàndiàn", "restaurant"),
    ("飞机", "fēijī", "aeroplane"),
    ("分钟", "fēnzhōng", "minute"),
    ("高兴", "gāoxìng", "happy"),
    ("个", "gè", "general measure word"),
    ("工作", "gōngzuò", "work; to work"),
    ("狗", "gǒu", "dog"),
    ("汉语", "Hànyǔ", "Chinese language"),
    ("好", "hǎo", "good"),
    ("号", "hào", "day of the month"),
    ("喝", "hē", "to drink"),
    ("和", "hé", "and; with"),
    ("很", "hěn", "very"),
    ("后面", "hòumiàn", "behind"),
    ("回", "huí", "to return"),
    ("会", "huì", "can; to know how to"),
    ("几", "jǐ", "how many"),
    ("家", "jiā", "home; family"),
    ("叫", "jiào", "to be called; to call"),
    ("今天", "jīntiān", "today"),
    ("九", "jiǔ", "nine"),
    ("开", "kāi", "to open; to drive"),
    ("看", "kàn", "to look; to watch"),
    ("看见", "kànjiàn", "to see"),
    ("块", "kuài", "unit of money"),
    ("来", "lái", "to come"),
    ("老师", "lǎoshī", "teacher"),
    ("了", "le", "completion particle"),
    ("冷", "lěng", "cold"),
    ("里", "lǐ", "inside"),
    ("六", "liù", "six"),
    ("妈妈", "māma", "mum"),
    ("吗", "ma", "question particle"),
    ("买", "mǎi", "to buy"),
    ("猫", "māo", "cat"),
    ("没关系", "méi guānxi", "it doesn't matter"),
    ("没有", "méiyǒu", "to not have; there is not"),
    ("米饭", "mǐfàn", "cooked rice"),
    ("名字", "míngzi", "name"),
    ("明天", "míngtiān", "tomorrow"),
    ("哪", "nǎ", "which"),
    ("哪儿", "nǎr", "where"),
    ("那", "nà", "that"),
    ("呢", "ne", "follow-up question particle"),
    ("能", "néng", "can; to be able to"),
    ("你", "nǐ", "you"),
    ("年", "nián", "year"),
    ("女儿", "nǚ'ér", "daughter"),
    ("朋友", "péngyou", "friend"),
    ("漂亮", "piàoliang", "pretty"),
    ("苹果", "píngguǒ", "apple"),
    ("七", "qī", "seven"),
    ("前面", "qiánmiàn", "in front"),
    ("钱", "qián", "money"),
    ("请", "qǐng", "please; to invite"),
    ("去", "qù", "to go"),
    ("热", "rè", "hot"),
    ("人", "rén", "person"),
    ("认识", "rènshi", "to know someone"),
    ("三", "sān", "three"),
    ("商店", "shāngdiàn", "shop"),
    ("上", "shàng", "on; above"),
    ("上午", "shàngwǔ", "morning"),
    ("少", "shǎo", "few; little"),
    ("谁", "shéi", "who"),
    ("什么", "shénme", "what"),
    ("十", "shí", "ten"),
    ("时候", "shíhou", "time; moment"),
    ("是", "shì", "to be"),
    ("书", "shū", "book"),
    ("水", "shuǐ", "water"),
    ("水果", "shuǐguǒ", "fruit"),
    ("睡觉", "shuìjiào", "to sleep"),
    ("说", "shuō", "to speak; to say"),
    ("四", "sì", "four"),
    ("岁", "suì", "year of age"),
    ("他", "tā", "he; him"),
    ("她", "tā", "she; her"),
    ("太", "tài", "too; extremely"),
    ("天气", "tiānqì", "weather"),
    ("听", "tīng", "to listen"),
    ("同学", "tóngxué", "classmate"),
    ("喂", "wèi", "hello (on the phone)"),
    ("我", "wǒ", "I; me"),
    ("我们", "wǒmen", "we; us"),
    ("五", "wǔ", "five"),
    ("喜欢", "xǐhuan", "to like"),
    ("下", "xià", "below; next"),
    ("下午", "xiàwǔ", "afternoon"),
    ("下雨", "xià yǔ", "to rain"),
    ("先生", "xiānsheng", "mister"),
    ("现在", "xiànzài", "now"),
    ("想", "xiǎng", "to want; to think"),
    ("小", "xiǎo", "small"),
    ("小姐", "xiǎojiě", "miss"),
    ("些", "xiē", "some"),
    ("写", "xiě", "to write"),
    ("谢谢", "xièxie", "thank you"),
    ("星期", "xīngqī", "week"),
    ("学生", "xuésheng", "student"),
    ("学习", "xuéxí", "to study"),
    ("学校", "xuéxiào", "school"),
    ("一", "yī", "one"),
    ("一点儿", "yìdiǎnr", "a little"),
    ("衣服", "yīfu", "clothes"),
    ("医生", "yīshēng", "doctor"),
    ("医院", "yīyuàn", "hospital"),
    ("椅子", "yǐzi", "chair"),
    ("有", "yǒu", "to have; there is"),
    ("月", "yuè", "month"),
    ("再见", "zàijiàn", "goodbye"),
    ("在", "zài", "at; in; on"),
    ("怎么", "zěnme", "how"),
    ("怎么样", "zěnmeyàng", "how about"),
    ("这", "zhè", "this"),
    ("中国", "Zhōngguó", "China"),
    ("中午", "zhōngwǔ", "noon"),
    ("住", "zhù", "to live; to stay"),
    ("桌子", "zhuōzi", "table"),
    ("字", "zì", "character"),
    ("昨天", "zuótiān", "yesterday"),
    ("坐", "zuò", "to sit; to travel by"),
    ("做", "zuò", "to do; to make"),
)

# The verbs a Newbie story should lean on again and again. A story that reuses
# eight of these across a dozen sentences teaches far more than one that uses
# thirty verbs once each.
HSK1_CORE_VERBS: tuple[str, ...] = (
    "是",
    "有",
    "没有",
    "在",
    "去",
    "来",
    "吃",
    "喝",
    "看",
    "看见",
    "说",
    "叫",
    "想",
    "喜欢",
    "会",
    "能",
    "买",
    "做",
    "坐",
    "住",
    "睡觉",
    "回",
    "开",
    "听",
    "认识",
    "工作",
    "学习",
    "打电话",
)

# Sentence patterns a Newbie story should recycle. Naming them keeps chapters
# structurally familiar, which is what makes a graded reader readable.
HSK1_PATTERNS: tuple[str, ...] = (
    "我是……",
    "我有……／我没有……",
    "我在……",
    "我想……",
    "我喜欢……",
    "这是什么？",
    "……好吗？",
    "……吗？",
    "我可以……吗？",
    "太……了！",
    "我也……",
    "我不……",
)


def word_budget_text() -> str:
    """The HSK 1 list as a compact prompt block."""
    return "、".join(f"{word}({pinyin})" for word, pinyin, _ in HSK1_WORDS)


def core_verbs_text() -> str:
    return "、".join(HSK1_CORE_VERBS)


def patterns_text() -> str:
    return "  ".join(HSK1_PATTERNS)
