export const SENTENCES = [
  { "mandarin": "你好！", "pinyin": "nǐ hǎo!", "translation": "Hello!", "stage": 1, "sub": 0 },
  { "mandarin": "今天天气很好。", "pinyin": "jīn tiān tiān qì hěn hǎo.", "translation": "The weather is very nice today.", "stage": 1, "sub": 0 },
  { "mandarin": "我是学生。", "pinyin": "wǒ shì xué sheng.", "translation": "I am a student.", "stage": 1, "sub": 0 },
  { "mandarin": "他是老师。", "pinyin": "tā shì lǎo shī.", "translation": "He is a teacher.", "stage": 1, "sub": 0 },
  { "mandarin": "他是中国人。", "pinyin": "tā shì zhōng guó rén.", "translation": "He is Chinese.", "stage": 1, "sub": 0 },
  { "mandarin": "她是我的朋友。", "pinyin": "tā shì wǒ de péng you.", "translation": "She is my friend.", "stage": 1, "sub": 0 },
  { "mandarin": "你好吗？", "pinyin": "nǐ hǎo ma?", "translation": "How are you?", "stage": 1, "sub": 0 },
  { "mandarin": "你觉得呢？", "pinyin": "nǐ jué de ne?", "translation": "What do you think?", "stage": 1, "sub": 0 },
  { "mandarin": "这是我的书。", "pinyin": "zhè shì wǒ de shū.", "translation": "This is my book.", "stage": 1, "sub": 0 },
  { "mandarin": "他去了学校。", "pinyin": "tā qù le xué xiào.", "translation": "He went to school.", "stage": 1, "sub": 0 },
  { "mandarin": "你好，很高兴认识你。", "pinyin": "nǐ hǎo, hěn gāo xìng rèn shi nǐ.", "translation": "Hello, nice to meet you.", "stage": 1, "sub": 1 },
  { "mandarin": "谢谢你！", "pinyin": "xiè xie nǐ!", "translation": "Thank you!", "stage": 1, "sub": 1 },
  { "mandarin": "再见，明天见！", "pinyin": "zài jiàn, míng tiān jiàn!", "translation": "Goodbye, see you tomorrow!", "stage": 1, "sub": 1 },
  { "mandarin": "请问，你是老师吗？", "pinyin": "qǐng wèn, nǐ shì lǎo shī ma?", "translation": "Excuse me, are you a teacher?", "stage": 1, "sub": 1 },
  { "mandarin": "对不起，我忘了。", "pinyin": "duì bu qǐ, wǒ wàng le.", "translation": "Sorry, I forgot.", "stage": 1, "sub": 1 },
  { "mandarin": "没关系！", "pinyin": "méi guān xi!", "translation": "It's okay!", "stage": 1, "sub": 1 },
  { "mandarin": "我可以喝水吗？", "pinyin": "wǒ kě yǐ hē shuǐ ma?", "translation": "May I drink water?", "stage": 1, "sub": 1 },
  { "mandarin": "我不知道。", "pinyin": "wǒ bù zhī dào.", "translation": "I don't know.", "stage": 1, "sub": 1 },
  { "mandarin": "你住在哪里？", "pinyin": "nǐ zhù zài nǎ lǐ?", "translation": "Where do you live?", "stage": 1, "sub": 1 },
  { "mandarin": "谁是你的朋友？", "pinyin": "shéi shì nǐ de péng you?", "translation": "Who is your friend?", "stage": 1, "sub": 1 },
  { "mandarin": "我爸爸很高。", "pinyin": "wǒ bà ba hěn gāo.", "translation": "My dad is very tall.", "stage": 1, "sub": 2 },
  { "mandarin": "我妈妈做的菜很好吃。", "pinyin": "wǒ mā ma zuò de cài hěn hǎo chī.", "translation": "My mom's cooking is delicious.", "stage": 1, "sub": 2 },
  { "mandarin": "我哥哥是学生。", "pinyin": "wǒ gē ge shì xué sheng.", "translation": "My older brother is a student.", "stage": 1, "sub": 2 },
  { "mandarin": "我姐姐很漂亮。", "pinyin": "wǒ jiě jie hěn piào liang.", "translation": "My older sister is very beautiful.", "stage": 1, "sub": 2 },
  { "mandarin": "中国很大。", "pinyin": "zhōng guó hěn dà.", "translation": "China is very big.", "stage": 1, "sub": 2 },
  { "mandarin": "这只猫很小。", "pinyin": "zhè zhī māo hěn xiǎo.", "translation": "This cat is very small.", "stage": 1, "sub": 2 },
  { "mandarin": "他是我的好朋友。", "pinyin": "tā shì wǒ de hǎo péng you.", "translation": "He is my good friend.", "stage": 1, "sub": 2 },
  { "mandarin": "我是大学生。", "pinyin": "wǒ shì dà xué shēng.", "translation": "I am a university student.", "stage": 1, "sub": 2 },
  { "mandarin": "张老师早上好。", "pinyin": "zhāng lǎo shī zǎo shang hǎo.", "translation": "Good morning, Teacher Zhang.", "stage": 1, "sub": 2 },
  { "mandarin": "很多人喜欢吃米饭。", "pinyin": "hěn duō rén xǐ huan chī mǐ fàn.", "translation": "Many people like to eat rice.", "stage": 1, "sub": 2 },
  { "mandarin": "你吃了吗？", "pinyin": "nǐ chī le ma?", "translation": "Have you eaten?", "stage": 1, "sub": 3 },
  { "mandarin": "我想喝水。", "pinyin": "wǒ xiǎng hē shuǐ.", "translation": "I want to drink water.", "stage": 1, "sub": 3 },
  { "mandarin": "请给我一杯水。", "pinyin": "qǐng gěi wǒ yī bēi shuǐ.", "translation": "Please give me a cup of water.", "stage": 1, "sub": 3 },
  { "mandarin": "我喜欢喝茶。", "pinyin": "wǒ xǐ huan hē chá.", "translation": "I like to drink tea.", "stage": 1, "sub": 3 },
  { "mandarin": "我要一杯咖啡。", "pinyin": "wǒ yào yī bēi kā fēi.", "translation": "I want a cup of coffee.", "stage": 1, "sub": 3 },
  { "mandarin": "孩子喝牛奶。", "pinyin": "hái zi hē niú nǎi.", "translation": "The child drinks milk.", "stage": 1, "sub": 3 },
  { "mandarin": "他不喝啤酒。", "pinyin": "tā bù hē pí jiǔ.", "translation": "He doesn't drink beer.", "stage": 1, "sub": 3 },
  { "mandarin": "我想吃米饭。", "pinyin": "wǒ xiǎng chī mǐ fàn.", "translation": "I want to eat rice.", "stage": 1, "sub": 3 },
  { "mandarin": "面条很好吃。", "pinyin": "miàn tiáo hěn hǎo chī.", "translation": "Noodles are delicious.", "stage": 1, "sub": 3 },
  { "mandarin": "这种水果很甜。", "pinyin": "zhè zhǒng shuǐ guǒ hěn tián.", "translation": "This kind of fruit is very sweet.", "stage": 1, "sub": 3 },
  { "mandarin": "她是一个好女人。", "pinyin": "tā shì yī gè hǎo nǚ rén.", "translation": "She is a good woman.", "stage": 1, "sub": 4 },
  { "mandarin": "草是绿色的。", "pinyin": "cǎo shì lǜ sè de.", "translation": "The grass is green.", "stage": 1, "sub": 4 },
  { "mandarin": "我去学校。", "pinyin": "wǒ qù xué xiào.", "translation": "I go to school.", "stage": 1, "sub": 4 },
  { "mandarin": "我喜欢吃鱼。", "pinyin": "wǒ xǐ huan chī yú.", "translation": "I like to eat fish.", "stage": 1, "sub": 4 },
  { "mandarin": "这个月很忙。", "pinyin": "zhè gè yuè hěn máng.", "translation": "This month is very busy.", "stage": 1, "sub": 4 },
  { "mandarin": "这个十块钱。", "pinyin": "zhè gè shí kuài qián.", "translation": "This is ten yuan.", "stage": 1, "sub": 4 },
  { "mandarin": "学校很远吗？", "pinyin": "xué xiào hěn yuǎn ma?", "translation": "Is the school far?", "stage": 1, "sub": 4 },
  { "mandarin": "今天下雨了。", "pinyin": "jīn tiān xià yǔ le.", "translation": "It's raining today.", "stage": 1, "sub": 4 },
  { "mandarin": "这条裙子很好看。", "pinyin": "zhè tiáo qún zi hěn hǎo kàn.", "translation": "This skirt is very pretty.", "stage": 1, "sub": 4 },
  { "mandarin": "你觉得怎么样？", "pinyin": "nǐ jué de zěn me yàng?", "translation": "What do you think?", "stage": 1, "sub": 4 },
  { "mandarin": "我有一个姐姐。", "pinyin": "wǒ yǒu yī gè jiě jie.", "translation": "I have one older sister.", "stage": 1, "sub": 5 },
  { "mandarin": "他有两个朋友。", "pinyin": "tā yǒu èr gè péng you.", "translation": "He has two friends.", "stage": 1, "sub": 5 },
  { "mandarin": "我有三本书。", "pinyin": "wǒ yǒu sān běn shū.", "translation": "I have three books.", "stage": 1, "sub": 5 },
  { "mandarin": "他有四个学生。", "pinyin": "tā yǒu sì gè xué shēng.", "translation": "He has four students.", "stage": 1, "sub": 5 },
  { "mandarin": "我要五杯水。", "pinyin": "wǒ yào wǔ bēi shuǐ.", "translation": "I want five cups of water.", "stage": 1, "sub": 5 },
  { "mandarin": "六个人来了。", "pinyin": "liù gè rén lái le.", "translation": "Six people came.", "stage": 1, "sub": 5 },
  { "mandarin": "今天是七月七号。", "pinyin": "jīn tiān shì qī yuè qī hào.", "translation": "Today is July 7th.", "stage": 1, "sub": 5 },
  { "mandarin": "八点上课。", "pinyin": "bā diǎn shàng kè.", "translation": "Class starts at eight.", "stage": 1, "sub": 5 },
  { "mandarin": "九月九号。", "pinyin": "jiǔ yuè jiǔ hào.", "translation": "September 9th.", "stage": 1, "sub": 5 },
  { "mandarin": "十个学生。", "pinyin": "shí gè xué shēng.", "translation": "Ten students.", "stage": 1, "sub": 5 },
  { "mandarin": "早上好，张老师！", "pinyin": "zǎo shang hǎo, zhāng lǎo shī!", "translation": "Good morning, Teacher Zhang!", "stage": 2, "sub": 0 },
  { "mandarin": "晚上好，你吃了吗？", "pinyin": "wǎn shang hǎo, nǐ chī le ma?", "translation": "Good evening, have you eaten?", "stage": 2, "sub": 0 },
  { "mandarin": "你好吗？我很好。", "pinyin": "nǐ hǎo ma? wǒ hěn hǎo.", "translation": "How are you? I'm very good.", "stage": 2, "sub": 0 },
  { "mandarin": "今天的天气很好。", "pinyin": "jīn tiān de tiān qì hěn hǎo.", "translation": "The weather is very good today.", "stage": 2, "sub": 0 },
  { "mandarin": "我也想去。", "pinyin": "wǒ yě xiǎng qù.", "translation": "I also want to go.", "stage": 2, "sub": 0 },
  { "mandarin": "明天见！", "pinyin": "míng tiān jiàn!", "translation": "See you tomorrow!", "stage": 2, "sub": 0 },
  { "mandarin": "欢迎你来中国！", "pinyin": "huān yíng nǐ lái zhōng guó!", "translation": "Welcome to China!", "stage": 2, "sub": 0 },
  { "mandarin": "拜拜，路上小心。", "pinyin": "bài bài, lù shàng xiǎo xīn.", "translation": "Bye-bye, be careful on the road.", "stage": 2, "sub": 0 },
  { "mandarin": "你叫什么名字？", "pinyin": "nǐ jiào shén me míng zi?", "translation": "What is your name?", "stage": 2, "sub": 0 },
  { "mandarin": "我的名字是王小明。", "pinyin": "wǒ de míng zi shì wáng xiǎo míng.", "translation": "My name is Wang Xiaoming.", "stage": 2, "sub": 0 },
  { "mandarin": "请坐。", "pinyin": "qǐng zuò.", "translation": "Please sit.", "stage": 2, "sub": 1 },
  { "mandarin": "不客气，应该的。", "pinyin": "bú kè qì, yīng gāi de.", "translation": "You're welcome, it's what I should do.", "stage": 2, "sub": 1 },
  { "mandarin": "麻烦你帮我一下。", "pinyin": "má fan nǐ bāng wǒ yī xià.", "translation": "Sorry to trouble you, help me a bit.", "stage": 2, "sub": 1 },
  { "mandarin": "你辛苦了！", "pinyin": "nǐ xīn kǔ le!", "translation": "Thanks for your hard work!", "stage": 2, "sub": 1 },
  { "mandarin": "不好意思打扰了。", "pinyin": "bù hǎo yì si dǎ rǎo le.", "translation": "Sorry to disturb you.", "stage": 2, "sub": 1 },
  { "mandarin": "我很抱歉。", "pinyin": "wǒ hěn bào qiàn.", "translation": "I am very sorry.", "stage": 2, "sub": 1 },
  { "mandarin": "你可以帮我吗？", "pinyin": "nǐ kě yǐ bāng wǒ ma?", "translation": "Can you help me?", "stage": 2, "sub": 1 },
  { "mandarin": "谢谢你！", "pinyin": "xiè xie nǐ!", "translation": "Thank you!", "stage": 2, "sub": 1 },
  { "mandarin": "你太客气了。", "pinyin": "nǐ tài kè qi le.", "translation": "You are too polite.", "stage": 2, "sub": 1 },
  { "mandarin": "你应该去看医生。", "pinyin": "nǐ yīng gāi qù kàn yī shēng.", "translation": "You should go see a doctor.", "stage": 2, "sub": 1 },
  { "mandarin": "你想吃什么？", "pinyin": "nǐ xiǎng chī shén me?", "translation": "What do you want to eat?", "stage": 2, "sub": 2 },
  { "mandarin": "你住在哪里？", "pinyin": "nǐ zhù zài nǎ lǐ?", "translation": "Where do you live?", "stage": 2, "sub": 2 },
  { "mandarin": "怎么去机场？", "pinyin": "zěn me qù jī chǎng?", "translation": "How do I get to the airport?", "stage": 2, "sub": 2 },
  { "mandarin": "这个多少钱？", "pinyin": "zhè gè duō shǎo qián?", "translation": "How much is this?", "stage": 2, "sub": 2 },
  { "mandarin": "你家有几口人？", "pinyin": "nǐ jiā yǒu jǐ kǒu rén?", "translation": "How many people are in your family?", "stage": 2, "sub": 2 },
  { "mandarin": "你为什么不去？", "pinyin": "nǐ wèi shén me bú qù?", "translation": "Why aren't you going?", "stage": 2, "sub": 2 },
  { "mandarin": "你喜欢哪个？", "pinyin": "nǐ xǐ huan nǎ gè?", "translation": "Which one do you like?", "stage": 2, "sub": 2 },
  { "mandarin": "你什么时候去？", "pinyin": "nǐ shén me shí hou qù?", "translation": "When are you going?", "stage": 2, "sub": 2 },
  { "mandarin": "你觉得怎么样？", "pinyin": "nǐ jué de zěn me yàng?", "translation": "What do you think?", "stage": 2, "sub": 2 },
  { "mandarin": "他来了吗？", "pinyin": "tā lái le ma?", "translation": "Has he come?", "stage": 2, "sub": 2 },
  { "mandarin": "请说慢一点。", "pinyin": "qǐng shuō màn yī diǎn.", "translation": "Please speak a bit slower.", "stage": 2, "sub": 3 },
  { "mandarin": "你说得太快了。", "pinyin": "nǐ shuō de tài kuài le.", "translation": "You speak too fast.", "stage": 2, "sub": 3 },
  { "mandarin": "我听不懂。", "pinyin": "wǒ tīng bù dǒng.", "translation": "I don't understand (when listening).", "stage": 2, "sub": 3 },
  { "mandarin": "你明白了吗？", "pinyin": "nǐ míng bai le ma?", "translation": "Do you understand?", "stage": 2, "sub": 3 },
  { "mandarin": "请打开课本。", "pinyin": "qǐng dǎ kāi kè běn.", "translation": "Please open the textbook.", "stage": 2, "sub": 3 },
  { "mandarin": "我的作业做完了。", "pinyin": "wǒ de zuò yè zuò wán le.", "translation": "I finished my homework.", "stage": 2, "sub": 3 },
  { "mandarin": "明天的考试很难。", "pinyin": "míng tiān de kǎo shì hěn nán.", "translation": "Tomorrow's exam is very hard.", "stage": 2, "sub": 3 },
  { "mandarin": "多做练习。", "pinyin": "duō zuò liàn xí.", "translation": "Do more practice exercises.", "stage": 2, "sub": 3 },
  { "mandarin": "我喜欢读书。", "pinyin": "wǒ xǐ huan dú shū.", "translation": "I like to read books.", "stage": 2, "sub": 3 },
  { "mandarin": "请写你的名字。", "pinyin": "qǐng xiě nǐ de míng zi.", "translation": "Please write your name.", "stage": 2, "sub": 3 },
  { "mandarin": "救命啊！", "pinyin": "jiù mìng a!", "translation": "Help!", "stage": 2, "sub": 4 },
  { "mandarin": "请帮个忙！", "pinyin": "qǐng bāng gè máng!", "translation": "Please give me a hand!", "stage": 2, "sub": 4 },
  { "mandarin": "我要去医院。", "pinyin": "wǒ yào qù yī yuàn.", "translation": "I need to go to the hospital.", "stage": 2, "sub": 4 },
  { "mandarin": "警察来了。", "pinyin": "jǐng chá lái le.", "translation": "The police have arrived.", "stage": 2, "sub": 4 },
  { "mandarin": "我的钱包丢了。", "pinyin": "wǒ de qián bāo diū le.", "translation": "I lost my wallet.", "stage": 2, "sub": 4 },
  { "mandarin": "你的电话号码是多少？", "pinyin": "nǐ de diàn huà hào mǎ shì duō shǎo?", "translation": "What is your phone number?", "stage": 2, "sub": 4 },
  { "mandarin": "小心火，这里危险。", "pinyin": "xiǎo xīn huǒ, zhè lǐ wēi xiǎn.", "translation": "Watch out for fire, it's dangerous here.", "stage": 2, "sub": 4 },
  { "mandarin": "有危险！", "pinyin": "yǒu wēi xiǎn!", "translation": "There is danger!", "stage": 2, "sub": 4 },
  { "mandarin": "我迷路了，帮帮我。", "pinyin": "wǒ mí lù le, bāng bang wǒ.", "translation": "I'm lost, help me.", "stage": 2, "sub": 4 },
  { "mandarin": "紧急出口在哪里？", "pinyin": "jǐn jí chū kǒu zài nǎ lǐ?", "translation": "Where is the emergency exit?", "stage": 2, "sub": 4 },
  { "mandarin": "好的，我马上去。", "pinyin": "hǎo de, wǒ mǎ shàng qù.", "translation": "Okay, I'll go right away.", "stage": 2, "sub": 5 },
  { "mandarin": "这个不行。", "pinyin": "zhè gè bù xíng.", "translation": "This won't work.", "stage": 2, "sub": 5 },
  { "mandarin": "我知道那个地方。", "pinyin": "wǒ zhī dào nà gè dì fang.", "translation": "I know that place.", "stage": 2, "sub": 5 },
  { "mandarin": "我不知道为什么。", "pinyin": "wǒ bù zhī dào wèi shén me.", "translation": "I don't know why.", "stage": 2, "sub": 5 },
  { "mandarin": "当然可以！", "pinyin": "dāng rán kě yǐ!", "translation": "Of course you can!", "stage": 2, "sub": 5 },
  { "mandarin": "明天可能下雨。", "pinyin": "míng tiān kě néng xià yǔ.", "translation": "It might rain tomorrow.", "stage": 2, "sub": 5 },
  { "mandarin": "没问题，我来帮你。", "pinyin": "méi wèn tí, wǒ lái bāng nǐ.", "translation": "No problem, I'll help you.", "stage": 2, "sub": 5 },
  { "mandarin": "这是真的吗？", "pinyin": "zhè shì zhēn de ma?", "translation": "Is this real?", "stage": 2, "sub": 5 },
  { "mandarin": "你说得对。", "pinyin": "nǐ shuō de duì.", "translation": "You are right.", "stage": 2, "sub": 5 },
  { "mandarin": "我想学中文。", "pinyin": "wǒ xiǎng xué zhōng wén.", "translation": "I want to learn Chinese.", "stage": 2, "sub": 5 },
  { "mandarin": "今天零度，很冷。", "pinyin": "jīn tiān líng dù, hěn lěng.", "translation": "It's zero degrees today, very cold.", "stage": 3, "sub": 0 },
  { "mandarin": "一百块钱。", "pinyin": "yī bǎi kuài qián.", "translation": "One hundred yuan.", "stage": 3, "sub": 0 },
  { "mandarin": "一千个学生。", "pinyin": "yī qiān gè xué shēng.", "translation": "One thousand students.", "stage": 3, "sub": 0 },
  { "mandarin": "一万块钱很多。", "pinyin": "yī wàn kuài qián hěn duō.", "translation": "Ten thousand yuan is a lot.", "stage": 3, "sub": 0 },
  { "mandarin": "今天是五号。", "pinyin": "jīn tiān shì wǔ hào.", "translation": "Today is the 5th.", "stage": 3, "sub": 0 },
  { "mandarin": "给我十块。", "pinyin": "gěi wǒ shí kuài.", "translation": "Give me ten yuan.", "stage": 3, "sub": 0 },
  { "mandarin": "你有钱吗？", "pinyin": "nǐ yǒu qián ma?", "translation": "Do you have money?", "stage": 3, "sub": 0 },
  { "mandarin": "我想买这本书。", "pinyin": "wǒ xiǎng mǎi zhè běn shū.", "translation": "I want to buy this book.", "stage": 3, "sub": 0 },
  { "mandarin": "他卖了车。", "pinyin": "tā mài le chē.", "translation": "He sold the car.", "stage": 3, "sub": 0 },
  { "mandarin": "这个太贵了。", "pinyin": "zhè gè tài guì le.", "translation": "This is too expensive.", "stage": 3, "sub": 0 },
  { "mandarin": "我是第一名。", "pinyin": "wǒ shì dì yī míng.", "translation": "I am first place.", "stage": 3, "sub": 1 },
  { "mandarin": "这个月很冷。", "pinyin": "zhè gè yuè hěn lěng.", "translation": "This month is very cold.", "stage": 3, "sub": 1 },
  { "mandarin": "今年是二零二六年。", "pinyin": "jīn nián shì èr líng èr liù nián.", "translation": "This year is 2026.", "stage": 3, "sub": 1 },
  { "mandarin": "今天星期五。", "pinyin": "jīn tiān xīng qī wǔ.", "translation": "Today is Friday.", "stage": 3, "sub": 1 },
  { "mandarin": "明天是我的生日。", "pinyin": "míng tiān shì wǒ de shēng rì.", "translation": "Tomorrow is my birthday.", "stage": 3, "sub": 1 },
  { "mandarin": "昨天我去医院了。", "pinyin": "zuó tiān wǒ qù yī yuàn le.", "translation": "Yesterday I went to the hospital.", "stage": 3, "sub": 1 },
  { "mandarin": "前天很热。", "pinyin": "qián tiān hěn rè.", "translation": "The day before yesterday was very hot.", "stage": 3, "sub": 1 },
  { "mandarin": "后天有空吗？", "pinyin": "hòu tiān yǒu kòng ma?", "translation": "Are you free the day after tomorrow?", "stage": 3, "sub": 1 },
  { "mandarin": "生日快乐！", "pinyin": "shēng rì kuài lè!", "translation": "Happy birthday!", "stage": 3, "sub": 1 },
  { "mandarin": "你什么时候去？", "pinyin": "nǐ shén me shí hou qù?", "translation": "When are you going?", "stage": 3, "sub": 1 },
  { "mandarin": "一个星期有七天。", "pinyin": "yī gè xīng qī yǒu qī tiān.", "translation": "A week has seven days.", "stage": 3, "sub": 2 },
  { "mandarin": "星期一我很忙。", "pinyin": "xīng qī yī wǒ hěn máng.", "translation": "I am very busy on Monday.", "stage": 3, "sub": 2 },
  { "mandarin": "星期二有考试。", "pinyin": "xīng qī èr yǒu kǎo shì.", "translation": "There is an exam on Tuesday.", "stage": 3, "sub": 2 },
  { "mandarin": "星期三下午没课。", "pinyin": "xīng qī sān xià wǔ méi kè.", "translation": "No class on Wednesday afternoon.", "stage": 3, "sub": 2 },
  { "mandarin": "星期四我去超市。", "pinyin": "xīng qī sì wǒ qù chāo shì.", "translation": "Thursday I go to the supermarket.", "stage": 3, "sub": 2 },
  { "mandarin": "星期五晚上见。", "pinyin": "xīng qī wǔ wǎn shang jiàn.", "translation": "See you Friday evening.", "stage": 3, "sub": 2 },
  { "mandarin": "星期六是周末。", "pinyin": "xīng qī liù shì zhōu mò.", "translation": "Saturday is the weekend.", "stage": 3, "sub": 2 },
  { "mandarin": "星期天我想休息。", "pinyin": "xīng qī tiān wǒ xiǎng xiū xi.", "translation": "On Sunday I want to rest.", "stage": 3, "sub": 2 },
  { "mandarin": "周末快乐！", "pinyin": "zhōu mò kuài lè!", "translation": "Happy weekend!", "stage": 3, "sub": 2 },
  { "mandarin": "今天天气很好。", "pinyin": "jīn tiān tiān qì hěn hǎo.", "translation": "The weather is very nice today.", "stage": 3, "sub": 2 },
  { "mandarin": "现在是几点？", "pinyin": "xiàn zài shì jǐ diǎn?", "translation": "What time is it now?", "stage": 3, "sub": 3 },
  { "mandarin": "三点十分开会。", "pinyin": "sān diǎn shí fēn kāi huì.", "translation": "The meeting starts at 3:10.", "stage": 3, "sub": 3 },
  { "mandarin": "现在是三点半。", "pinyin": "xiàn zài shì sān diǎn bàn.", "translation": "It is now 3:30.", "stage": 3, "sub": 3 },
  { "mandarin": "两点一刻到。", "pinyin": "liǎng diǎn yī kè dào.", "translation": "Arrive at 2:15.", "stage": 3, "sub": 3 },
  { "mandarin": "早上好！", "pinyin": "zǎo shang hǎo!", "translation": "Good morning!", "stage": 3, "sub": 3 },
  { "mandarin": "中午我们吃饭吧。", "pinyin": "zhōng wǔ wǒ men chī fàn ba.", "translation": "Let's eat at noon.", "stage": 3, "sub": 3 },
  { "mandarin": "下午陪我去。", "pinyin": "xià wǔ péi wǒ qù.", "translation": "Accompany me this afternoon.", "stage": 3, "sub": 3 },
  { "mandarin": "晚上你有空吗？", "pinyin": "wǎn shang nǐ yǒu kòng ma?", "translation": "Are you free this evening?", "stage": 3, "sub": 3 },
  { "mandarin": "现在几点了？", "pinyin": "xiàn zài jǐ diǎn le?", "translation": "What time is it now?", "stage": 3, "sub": 3 },
  { "mandarin": "时间过得很快。", "pinyin": "shí jiān guò de hěn kuài.", "translation": "Time passes very quickly.", "stage": 3, "sub": 3 },
  { "mandarin": "等我五分钟。", "pinyin": "děng wǒ wǔ fēn zhōng.", "translation": "Wait five minutes for me.", "stage": 3, "sub": 4 },
  { "mandarin": "一个小时很长。", "pinyin": "yī gè xiǎo shí hěn cháng.", "translation": "One hour is very long.", "stage": 3, "sub": 4 },
  { "mandarin": "一周有七天。", "pinyin": "yī zhōu yǒu qī tiān.", "translation": "A week has seven days.", "stage": 3, "sub": 4 },
  { "mandarin": "一个月有三十天。", "pinyin": "yī gè yuè yǒu sān shí tiān.", "translation": "A month has thirty days.", "stage": 3, "sub": 4 },
  { "mandarin": "这条路很长。", "pinyin": "zhè tiáo lù hěn cháng.", "translation": "This road is very long.", "stage": 3, "sub": 4 },
  { "mandarin": "时间很短。", "pinyin": "shí jiān hěn duǎn.", "translation": "Time is short.", "stage": 3, "sub": 4 },
  { "mandarin": "你吃得太快了。", "pinyin": "nǐ chī de tài kuài le.", "translation": "You eat too fast.", "stage": 3, "sub": 4 },
  { "mandarin": "请说慢一点。", "pinyin": "qǐng shuō màn yī diǎn.", "translation": "Please speak a bit slower.", "stage": 3, "sub": 4 },
  { "mandarin": "好久不见！", "pinyin": "hǎo jiǔ bú jiàn!", "translation": "Long time no see!", "stage": 3, "sub": 4 },
  { "mandarin": "我买了一件新裙子。", "pinyin": "wǒ mǎi le yī jiàn xīn qún zi.", "translation": "I bought a new skirt.", "stage": 3, "sub": 4 },
  { "mandarin": "我二十五岁。", "pinyin": "wǒ èr shí wǔ suì.", "translation": "I am twenty-five years old.", "stage": 3, "sub": 5 },
  { "mandarin": "你很年轻。", "pinyin": "nǐ hěn nián qīng.", "translation": "You are very young.", "stage": 3, "sub": 5 },
  { "mandarin": "他很老了。", "pinyin": "tā hěn lǎo le.", "translation": "He is very old.", "stage": 3, "sub": 5 },
  { "mandarin": "我们给妈妈过生日。", "pinyin": "wǒ men gěi mā ma guò shēng rì.", "translation": "We celebrate mom's birthday.", "stage": 3, "sub": 5 },
  { "mandarin": "你今年多大？", "pinyin": "nǐ jīn nián duō dà?", "translation": "How old are you this year?", "stage": 3, "sub": 5 },
  { "mandarin": "我出生在北京。", "pinyin": "wǒ chū shēng zài běi jīng.", "translation": "I was born in Beijing.", "stage": 3, "sub": 5 },
  { "mandarin": "我喜欢吃中国菜。", "pinyin": "wǒ xǐ huan chī zhōng guó cài.", "translation": "I like to eat Chinese food.", "stage": 3, "sub": 5 },
  { "mandarin": "我要一杯水。", "pinyin": "wǒ yào yī bēi shuǐ.", "translation": "I want a cup of water.", "stage": 3, "sub": 5 },
  { "mandarin": "你会说中文吗？", "pinyin": "nǐ huì shuō zhōng wén ma?", "translation": "Can you speak Chinese?", "stage": 3, "sub": 5 },
  { "mandarin": "你能帮我吗？", "pinyin": "nǐ néng bāng wǒ ma?", "translation": "Can you help me?", "stage": 3, "sub": 5 }
];
