export const VOCAB = [
  { id: 1,  char: '你', pinyin: 'nǐ',  meaning: 'you',              tone: 3, stage: 1, sub: 0 },
  { id: 2,  char: '好', pinyin: 'hǎo', meaning: 'good',             tone: 3, stage: 1, sub: 0 },
  { id: 3,  char: '我', pinyin: 'wǒ',  meaning: 'I / me',           tone: 3, stage: 1, sub: 0 },
  { id: 4,  char: '是', pinyin: 'shì', meaning: 'am / is / are',    tone: 4, stage: 1, sub: 0 },
  { id: 5,  char: '他', pinyin: 'tā',  meaning: 'he / him',         tone: 1, stage: 1, sub: 0 },
  { id: 6,  char: '她', pinyin: 'tā',  meaning: 'she / her',        tone: 1, stage: 1, sub: 0 },
  { id: 7,  char: '吗', pinyin: 'ma',  meaning: 'question particle',tone: 0, stage: 1, sub: 0 },
  { id: 8,  char: '呢', pinyin: 'ne',  meaning: 'modal particle',   tone: 0, stage: 1, sub: 0 },
  { id: 9,  char: '的', pinyin: 'de',  meaning: 'possessive particle',tone:0, stage: 1, sub: 0 },
  { id: 10, char: '了', pinyin: 'le',  meaning: 'change particle',  tone: 0, stage: 1, sub: 0 },
  { id: 11, char: '你好', pinyin: 'nǐ hǎo', meaning: 'hello',           tone: 0, stage: 1, sub: 1 },
  { id: 12, char: '谢谢', pinyin: 'xiè xie', meaning: 'thank you',      tone: 0, stage: 1, sub: 1 },
  { id: 13, char: '再见', pinyin: 'zài jiàn', meaning: 'goodbye',        tone: 0, stage: 1, sub: 1 },
  { id: 14, char: '请问', pinyin: 'qǐng wèn', meaning: 'may I ask',     tone: 0, stage: 1, sub: 1 },
  { id: 15, char: '对不起', pinyin: 'duì bu qǐ', meaning: 'sorry',      tone: 0, stage: 1, sub: 1 },
  { id: 16, char: '没关系', pinyin: 'méi guān xi', meaning: "it's okay", tone: 0, stage: 1, sub: 1 },
  { id: 17, char: '可以', pinyin: 'kě yǐ', meaning: 'can / may',        tone: 0, stage: 1, sub: 1 },
  { id: 18, char: '不', pinyin: 'bù',  meaning: 'not',                   tone: 4, stage: 1, sub: 1 },
  { id: 19, char: '哪', pinyin: 'nǎ',  meaning: 'which / where',        tone: 3, stage: 1, sub: 1 },
  { id: 20, char: '谁', pinyin: 'shéi',meaning: 'who',                   tone: 2, stage: 1, sub: 1 },
  { id: 21, char: '爸', pinyin: 'bà',    meaning: 'father',        tone: 4, stage: 1, sub: 2 },
  { id: 22, char: '妈', pinyin: 'mā',    meaning: 'mother',        tone: 1, stage: 1, sub: 2 },
  { id: 23, char: '哥', pinyin: 'gē',    meaning: 'older brother', tone: 1, stage: 1, sub: 2 },
  { id: 24, char: '姐', pinyin: 'jiě',   meaning: 'older sister',  tone: 3, stage: 1, sub: 2 },
  { id: 25, char: '大', pinyin: 'dà',    meaning: 'big',           tone: 4, stage: 1, sub: 2 },
  { id: 26, char: '小', pinyin: 'xiǎo',  meaning: 'small',         tone: 3, stage: 1, sub: 2 },
  { id: 27, char: '朋友', pinyin: 'péng you', meaning: 'friend',   tone: 0, stage: 1, sub: 2 },
  { id: 28, char: '学生', pinyin: 'xué sheng', meaning: 'student', tone: 0, stage: 1, sub: 2 },
  { id: 29, char: '老师', pinyin: 'lǎo shī', meaning: 'teacher',   tone: 0, stage: 1, sub: 2 },
  { id: 30, char: '人', pinyin: 'rén',   meaning: 'person',        tone: 2, stage: 1, sub: 2 },
  { id: 31, char: '吃', pinyin: 'chī',      meaning: 'eat',     tone: 1, stage: 1, sub: 3 },
  { id: 32, char: '喝', pinyin: 'hē',       meaning: 'drink',   tone: 1, stage: 1, sub: 3 },
  { id: 33, char: '水', pinyin: 'shuǐ',     meaning: 'water',   tone: 3, stage: 1, sub: 3 },
  { id: 34, char: '茶', pinyin: 'chá',      meaning: 'tea',     tone: 2, stage: 1, sub: 3 },
  { id: 35, char: '咖啡', pinyin: 'kā fēi', meaning: 'coffee',  tone: 0, stage: 1, sub: 3 },
  { id: 36, char: '牛奶', pinyin: 'niú nǎi',meaning: 'milk',    tone: 0, stage: 1, sub: 3 },
  { id: 37, char: '啤酒', pinyin: 'pí jiǔ', meaning: 'beer',     tone: 0, stage: 1, sub: 3 },
  { id: 38, char: '米饭', pinyin: 'mǐ fàn', meaning: 'rice',     tone: 0, stage: 1, sub: 3 },
  { id: 39, char: '面条', pinyin: 'miàn tiáo', meaning: 'noodles',tone: 0, stage: 1, sub: 3 },
  { id: 40, char: '水果', pinyin: 'shuǐ guǒ', meaning: 'fruit',  tone: 0, stage: 1, sub: 3 },
  { id: 41, char: '女', pinyin: 'nǚ',    meaning: 'woman / female', tone: 3, stage: 1, sub: 4 },
  { id: 42, char: '绿', pinyin: 'lǜ',    meaning: 'green',          tone: 4, stage: 1, sub: 4 },
  { id: 43, char: '去', pinyin: 'qù',    meaning: 'go',             tone: 4, stage: 1, sub: 4 },
  { id: 44, char: '鱼', pinyin: 'yú',    meaning: 'fish',           tone: 2, stage: 1, sub: 4 },
  { id: 45, char: '月', pinyin: 'yuè',   meaning: 'moon / month',   tone: 4, stage: 1, sub: 4 },
  { id: 46, char: '元', pinyin: 'yuán',  meaning: 'yuan (currency)',tone: 2, stage: 1, sub: 4 },
  { id: 47, char: '远', pinyin: 'yuǎn',  meaning: 'far',            tone: 3, stage: 1, sub: 4 },
  { id: 48, char: '雨', pinyin: 'yǔ',    meaning: 'rain',           tone: 3, stage: 1, sub: 4 },
  { id: 49, char: '裙子', pinyin: 'qún zi', meaning: 'skirt',      tone: 0, stage: 1, sub: 4 },
  { id: 50, char: '觉得', pinyin: 'jué de', meaning: 'feel / think',tone: 0, stage: 1, sub: 4 },
  { id: 51, char: '一', pinyin: 'yī',  meaning: 'one',   tone: 1, stage: 1, sub: 5 },
  { id: 52, char: '二', pinyin: 'èr',  meaning: 'two',   tone: 4, stage: 1, sub: 5 },
  { id: 53, char: '三', pinyin: 'sān', meaning: 'three', tone: 1, stage: 1, sub: 5 },
  { id: 54, char: '四', pinyin: 'sì',  meaning: 'four',  tone: 4, stage: 1, sub: 5 },
  { id: 55, char: '五', pinyin: 'wǔ',  meaning: 'five',  tone: 3, stage: 1, sub: 5 },
  { id: 56, char: '六', pinyin: 'liù', meaning: 'six',   tone: 4, stage: 1, sub: 5 },
  { id: 57, char: '七', pinyin: 'qī',  meaning: 'seven', tone: 1, stage: 1, sub: 5 },
  { id: 58, char: '八', pinyin: 'bā',  meaning: 'eight', tone: 1, stage: 1, sub: 5 },
  { id: 59, char: '九', pinyin: 'jiǔ', meaning: 'nine',  tone: 3, stage: 1, sub: 5 },
  { id: 60, char: '十', pinyin: 'shí', meaning: 'ten',   tone: 2, stage: 1, sub: 5 },
  { id: 61, char: '早上好', pinyin: 'zǎo shang hǎo', meaning: 'good morning',  tone: 0, stage: 2, sub: 0 },
  { id: 62, char: '晚上好', pinyin: 'wǎn shang hǎo', meaning: 'good evening',  tone: 0, stage: 2, sub: 0 },
  { id: 63, char: '你好吗', pinyin: 'nǐ hǎo ma',     meaning: 'how are you',   tone: 0, stage: 2, sub: 0 },
  { id: 64, char: '很好', pinyin: 'hěn hǎo',         meaning: 'very good',     tone: 0, stage: 2, sub: 0 },
  { id: 65, char: '也', pinyin: 'yě',                meaning: 'also',          tone: 3, stage: 2, sub: 0 },
  { id: 66, char: '明天见', pinyin: 'míng tiān jiàn', meaning: 'see you tomorrow',tone: 0, stage: 2, sub: 0 },
  { id: 67, char: '欢迎', pinyin: 'huān yíng',       meaning: 'welcome',       tone: 0, stage: 2, sub: 0 },
  { id: 68, char: '拜拜', pinyin: 'bài bài',         meaning: 'bye-bye',       tone: 0, stage: 2, sub: 0 },
  { id: 69, char: '叫', pinyin: 'jiào',              meaning: 'to be called',  tone: 4, stage: 2, sub: 0 },
  { id: 70, char: '名字', pinyin: 'míng zi',         meaning: 'name',          tone: 0, stage: 2, sub: 0 },
  { id: 71, char: '请', pinyin: 'qǐng',      meaning: 'please',              tone: 3, stage: 2, sub: 1 },
  { id: 72, char: '不客气', pinyin: 'bú kè qì', meaning: "you're welcome",   tone: 0, stage: 2, sub: 1 },
  { id: 73, char: '麻烦', pinyin: 'má fan',   meaning: 'to trouble',         tone: 0, stage: 2, sub: 1 },
  { id: 74, char: '辛苦了', pinyin: 'xīn kǔ le', meaning: 'thanks for your hard work', tone: 0, stage: 2, sub: 1 },
  { id: 75, char: '打扰', pinyin: 'dǎ rǎo',   meaning: 'to disturb',         tone: 0, stage: 2, sub: 1 },
  { id: 76, char: '抱歉', pinyin: 'bào qiàn', meaning: 'to feel sorry',       tone: 0, stage: 2, sub: 1 },
  { id: 77, char: '帮', pinyin: 'bāng',       meaning: 'to help',             tone: 1, stage: 2, sub: 1 },
  { id: 78, char: '谢', pinyin: 'xiè',        meaning: 'to thank',            tone: 4, stage: 2, sub: 1 },
  { id: 79, char: '客气', pinyin: 'kè qi',    meaning: 'polite / courteous',  tone: 0, stage: 2, sub: 1 },
  { id: 80, char: '应该', pinyin: 'yīng gāi', meaning: 'should',              tone: 0, stage: 2, sub: 1 },
  { id: 81, char: '什么', pinyin: 'shén me',   meaning: 'what',       tone: 0, stage: 2, sub: 2 },
  { id: 82, char: '哪里', pinyin: 'nǎ lǐ',     meaning: 'where',      tone: 0, stage: 2, sub: 2 },
  { id: 83, char: '怎么', pinyin: 'zěn me',    meaning: 'how',        tone: 0, stage: 2, sub: 2 },
  { id: 84, char: '多少', pinyin: 'duō shao',   meaning: 'how many / how much', tone: 0, stage: 2, sub: 2 },
  { id: 85, char: '几', pinyin: 'jǐ',          meaning: 'how many (small number)', tone: 3, stage: 2, sub: 2 },
  { id: 86, char: '为什么', pinyin: 'wèi shén me', meaning: 'why',    tone: 0, stage: 2, sub: 2 },
  { id: 87, char: '哪个', pinyin: 'nǎ ge',     meaning: 'which one',  tone: 0, stage: 2, sub: 2 },
  { id: 88, char: '什么时候', pinyin: 'shén me shí hou', meaning: 'when', tone: 0, stage: 2, sub: 2 },
  { id: 89, char: '怎么样', pinyin: 'zěn me yàng', meaning: 'how about', tone: 0, stage: 2, sub: 2 },
  { id: 90, char: '多久', pinyin: 'duō jiǔ',   meaning: 'how long',    tone: 0, stage: 2, sub: 2 },
  { id: 91, char: '说', pinyin: 'shuō',        meaning: 'to speak',   tone: 1, stage: 2, sub: 3 },
  { id: 92, char: '慢', pinyin: 'màn',         meaning: 'slow',       tone: 4, stage: 2, sub: 3 },
  { id: 93, char: '懂', pinyin: 'dǒng',        meaning: 'to understand', tone: 3, stage: 2, sub: 3 },
  { id: 94, char: '明白', pinyin: 'míng bai',  meaning: 'to understand / clear', tone: 0, stage: 2, sub: 3 },
  { id: 95, char: '课本', pinyin: 'kè běn',    meaning: 'textbook',   tone: 0, stage: 2, sub: 3 },
  { id: 96, char: '作业', pinyin: 'zuò yè',    meaning: 'homework',   tone: 0, stage: 2, sub: 3 },
  { id: 97, char: '考试', pinyin: 'kǎo shì',   meaning: 'exam',       tone: 0, stage: 2, sub: 3 },
  { id: 98, char: '练习', pinyin: 'liàn xí',   meaning: 'to practice',tone: 0, stage: 2, sub: 3 },
  { id: 99, char: '读', pinyin: 'dú',          meaning: 'to read',    tone: 2, stage: 2, sub: 3 },
  { id: 100, char: '写', pinyin: 'xiě',        meaning: 'to write',   tone: 3, stage: 2, sub: 3 },
  { id: 101, char: '救命', pinyin: 'jiù mìng', meaning: 'help! / save me', tone: 0, stage: 2, sub: 4 },
  { id: 102, char: '帮忙', pinyin: 'bāng máng',meaning: 'to help',        tone: 0, stage: 2, sub: 4 },
  { id: 103, char: '医院', pinyin: 'yī yuàn',  meaning: 'hospital',       tone: 0, stage: 2, sub: 4 },
  { id: 104, char: '警察', pinyin: 'jǐng chá', meaning: 'police',         tone: 0, stage: 2, sub: 4 },
  { id: 105, char: '丢了', pinyin: 'diū le',   meaning: 'lost',           tone: 0, stage: 2, sub: 4 },
  { id: 106, char: '电话', pinyin: 'diàn huà', meaning: 'telephone',      tone: 0, stage: 2, sub: 4 },
  { id: 107, char: '火', pinyin: 'huǒ',        meaning: 'fire',           tone: 3, stage: 2, sub: 4 },
  { id: 108, char: '危险', pinyin: 'wēi xiǎn', meaning: 'dangerous',      tone: 0, stage: 2, sub: 4 },
  { id: 109, char: '迷路', pinyin: 'mí lù',    meaning: 'to get lost',    tone: 0, stage: 2, sub: 4 },
  { id: 110, char: '紧急', pinyin: 'jǐn jí',   meaning: 'urgent / emergency', tone: 0, stage: 2, sub: 4 },
  { id: 111, char: '好的', pinyin: 'hǎo de',    meaning: 'okay / alright', tone: 0, stage: 2, sub: 5 },
  { id: 112, char: '不行', pinyin: 'bù xíng',  meaning: 'not okay / no way', tone: 0, stage: 2, sub: 5 },
  { id: 113, char: '知道', pinyin: 'zhī dao',   meaning: 'to know',        tone: 0, stage: 2, sub: 5 },
  { id: 114, char: '不知道', pinyin: 'bù zhī dao', meaning: "don't know", tone: 0, stage: 2, sub: 5 },
  { id: 115, char: '当然', pinyin: 'dāng rán',  meaning: 'of course',      tone: 0, stage: 2, sub: 5 },
  { id: 116, char: '可能', pinyin: 'kě néng',   meaning: 'maybe / possible', tone: 0, stage: 2, sub: 5 },
  { id: 117, char: '没问题', pinyin: 'méi wèn tí', meaning: 'no problem', tone: 0, stage: 2, sub: 5 },
  { id: 118, char: '真的', pinyin: 'zhēn de',   meaning: 'really',         tone: 0, stage: 2, sub: 5 },
  { id: 119, char: '对', pinyin: 'duì',         meaning: 'correct / right',tone: 4, stage: 2, sub: 5 },
  { id: 120, char: '想', pinyin: 'xiǎng',       meaning: 'to want / to think', tone: 3, stage: 2, sub: 5 },
  { id: 121, char: '零', pinyin: 'líng', meaning: 'zero',   tone: 2, stage: 3, sub: 0 },
  { id: 122, char: '百', pinyin: 'bǎi', meaning: 'hundred', tone: 3, stage: 3, sub: 0 },
  { id: 123, char: '千', pinyin: 'qiān',meaning: 'thousand',tone: 1, stage: 3, sub: 0 },
  { id: 124, char: '万', pinyin: 'wàn', meaning: 'ten thousand', tone: 4, stage: 3, sub: 0 },
  { id: 125, char: '号', pinyin: 'hào', meaning: 'number',  tone: 4, stage: 3, sub: 0 },
  { id: 126, char: '块', pinyin: 'kuài',meaning: 'dollar / yuan (colloquial)', tone: 4, stage: 3, sub: 0 },
  { id: 127, char: '钱', pinyin: 'qián',meaning: 'money',   tone: 2, stage: 3, sub: 0 },
  { id: 128, char: '买', pinyin: 'mǎi', meaning: 'to buy',  tone: 3, stage: 3, sub: 0 },
  { id: 129, char: '卖', pinyin: 'mài', meaning: 'to sell', tone: 4, stage: 3, sub: 0 },
  { id: 130, char: '贵', pinyin: 'guì', meaning: 'expensive', tone: 4, stage: 3, sub: 0 },
  { id: 131, char: '第', pinyin: 'dì',      meaning: 'ordinal prefix', tone: 4, stage: 3, sub: 1 },
  { id: 132, char: '月', pinyin: 'yuè',     meaning: 'month',          tone: 4, stage: 3, sub: 1 },
  { id: 133, char: '年', pinyin: 'nián',    meaning: 'year',           tone: 2, stage: 3, sub: 1 },
  { id: 134, char: '今天', pinyin: 'jīn tiān', meaning: 'today',      tone: 0, stage: 3, sub: 1 },
  { id: 135, char: '明天', pinyin: 'míng tiān', meaning: 'tomorrow',   tone: 0, stage: 3, sub: 1 },
  { id: 136, char: '昨天', pinyin: 'zuó tiān', meaning: 'yesterday',   tone: 0, stage: 3, sub: 1 },
  { id: 137, char: '前天', pinyin: 'qián tiān', meaning: 'day before yesterday', tone: 0, stage: 3, sub: 1 },
  { id: 138, char: '后天', pinyin: 'hòu tiān', meaning: 'day after tomorrow',    tone: 0, stage: 3, sub: 1 },
  { id: 139, char: '生日', pinyin: 'shēng rì', meaning: 'birthday',    tone: 0, stage: 3, sub: 1 },
  { id: 140, char: '时候', pinyin: 'shí hou', meaning: 'time / moment', tone: 0, stage: 3, sub: 1 },
  { id: 141, char: '星期', pinyin: 'xīng qī', meaning: 'week',         tone: 0, stage: 3, sub: 2 },
  { id: 142, char: '星期一', pinyin: 'xīng qī yī', meaning: 'Monday',  tone: 0, stage: 3, sub: 2 },
  { id: 143, char: '星期二', pinyin: 'xīng qī èr', meaning: 'Tuesday', tone: 0, stage: 3, sub: 2 },
  { id: 144, char: '星期三', pinyin: 'xīng qī sān', meaning: 'Wednesday', tone: 0, stage: 3, sub: 2 },
  { id: 145, char: '星期四', pinyin: 'xīng qī sì', meaning: 'Thursday', tone: 0, stage: 3, sub: 2 },
  { id: 146, char: '星期五', pinyin: 'xīng qī wǔ', meaning: 'Friday',  tone: 0, stage: 3, sub: 2 },
  { id: 147, char: '星期六', pinyin: 'xīng qī liù', meaning: 'Saturday', tone: 0, stage: 3, sub: 2 },
  { id: 148, char: '星期天', pinyin: 'xīng qī tiān', meaning: 'Sunday', tone: 0, stage: 3, sub: 2 },
  { id: 149, char: '周末', pinyin: 'zhōu mò', meaning: 'weekend',       tone: 0, stage: 3, sub: 2 },
  { id: 150, char: '天', pinyin: 'tiān',      meaning: 'day / sky',     tone: 1, stage: 3, sub: 2 },
  { id: 151, char: '点', pinyin: 'diǎn',       meaning: "o'clock",    tone: 3, stage: 3, sub: 3 },
  { id: 152, char: '分', pinyin: 'fēn',        meaning: 'minute',     tone: 1, stage: 3, sub: 3 },
  { id: 153, char: '半', pinyin: 'bàn',        meaning: 'half',       tone: 4, stage: 3, sub: 3 },
  { id: 154, char: '刻', pinyin: 'kè',         meaning: 'quarter (hour)', tone: 4, stage: 3, sub: 3 },
  { id: 155, char: '早上', pinyin: 'zǎo shang',meaning: 'morning',    tone: 0, stage: 3, sub: 3 },
  { id: 156, char: '中午', pinyin: 'zhōng wǔ', meaning: 'noon',       tone: 0, stage: 3, sub: 3 },
  { id: 157, char: '下午', pinyin: 'xià wǔ',   meaning: 'afternoon',  tone: 0, stage: 3, sub: 3 },
  { id: 158, char: '晚上', pinyin: 'wǎn shang',meaning: 'evening',    tone: 0, stage: 3, sub: 3 },
  { id: 159, char: '现在', pinyin: 'xiàn zài', meaning: 'now',         tone: 0, stage: 3, sub: 3 },
  { id: 160, char: '时间', pinyin: 'shí jiān', meaning: 'time',        tone: 0, stage: 3, sub: 3 },
  { id: 161, char: '分钟', pinyin: 'fēn zhōng', meaning: 'minute (duration)', tone: 0, stage: 3, sub: 4 },
  { id: 162, char: '小时', pinyin: 'xiǎo shí', meaning: 'hour',        tone: 0, stage: 3, sub: 4 },
  { id: 163, char: '周', pinyin: 'zhōu',       meaning: 'week',        tone: 1, stage: 3, sub: 4 },
  { id: 164, char: '个月', pinyin: 'gè yuè',   meaning: 'month (duration)', tone: 0, stage: 3, sub: 4 },
  { id: 165, char: '长', pinyin: 'cháng',      meaning: 'long',        tone: 2, stage: 3, sub: 4 },
  { id: 166, char: '短', pinyin: 'duǎn',       meaning: 'short',       tone: 3, stage: 3, sub: 4 },
  { id: 167, char: '快', pinyin: 'kuài',       meaning: 'fast',        tone: 4, stage: 3, sub: 4 },
  { id: 168, char: '慢', pinyin: 'màn',        meaning: 'slow',        tone: 4, stage: 3, sub: 4 },
  { id: 169, char: '久', pinyin: 'jiǔ',        meaning: 'long (time)', tone: 3, stage: 3, sub: 4 },
  { id: 170, char: '新', pinyin: 'xīn',        meaning: 'new',         tone: 1, stage: 3, sub: 4 },
  { id: 171, char: '岁', pinyin: 'suì',        meaning: 'years old',   tone: 4, stage: 3, sub: 5 },
  { id: 172, char: '年轻', pinyin: 'nián qīng',meaning: 'young',       tone: 0, stage: 3, sub: 5 },
  { id: 173, char: '老', pinyin: 'lǎo',        meaning: 'old',         tone: 3, stage: 3, sub: 5 },
  { id: 174, char: '过生日', pinyin: 'guò shēng rì', meaning: 'to celebrate birthday', tone: 0, stage: 3, sub: 5 },
  { id: 175, char: '多大', pinyin: 'duō dà',   meaning: 'how old',     tone: 0, stage: 3, sub: 5 },
  { id: 176, char: '出生', pinyin: 'chū shēng',meaning: 'to be born',  tone: 0, stage: 3, sub: 5 },
  { id: 177, char: '喜欢', pinyin: 'xǐ huan',  meaning: 'to like',     tone: 0, stage: 3, sub: 5 },
  { id: 178, char: '要', pinyin: 'yào',        meaning: 'to want / will', tone: 4, stage: 3, sub: 5 },
  { id: 179, char: '会', pinyin: 'huì',        meaning: 'can / will',  tone: 4, stage: 3, sub: 5 },
  { id: 180, char: '能', pinyin: 'néng',       meaning: 'can / able to', tone: 2, stage: 3, sub: 5 },

  // --- Phase 2: Core Vocabulary ---

  // Stage 4 — People & Pronouns
  { id: 181, char: '我们', pinyin: 'wǒ men',    meaning: 'we / us',                    tone: 0, stage: 4, sub: 0 },
  { id: 182, char: '你们', pinyin: 'nǐ men',    meaning: 'you (plural)',               tone: 0, stage: 4, sub: 0 },
  { id: 183, char: '他们', pinyin: 'tā men',    meaning: 'they (masculine/mixed)',     tone: 0, stage: 4, sub: 0 },
  { id: 184, char: '她们', pinyin: 'tā men',    meaning: 'they (feminine)',            tone: 0, stage: 4, sub: 0 },
  { id: 185, char: '自己', pinyin: 'zì jǐ',     meaning: 'self / oneself',             tone: 0, stage: 4, sub: 0 },
  { id: 186, char: '大家', pinyin: 'dà jiā',    meaning: 'everyone',                   tone: 0, stage: 4, sub: 0 },
  { id: 187, char: '别人', pinyin: 'bié rén',   meaning: 'other people / others',      tone: 0, stage: 4, sub: 0 },
  { id: 188, char: '任何', pinyin: 'rèn hé',    meaning: 'any / whatever',             tone: 0, stage: 4, sub: 0 },
  { id: 189, char: '一切', pinyin: 'yī qiè',    meaning: 'everything / all',           tone: 0, stage: 4, sub: 0 },
  { id: 190, char: '各自', pinyin: 'gè zì',     meaning: 'each / respectively',        tone: 0, stage: 4, sub: 0 },

  { id: 191, char: '弟弟', pinyin: 'dì di',     meaning: 'younger brother',            tone: 0, stage: 4, sub: 1 },
  { id: 192, char: '妹妹', pinyin: 'mèi mei',   meaning: 'younger sister',             tone: 0, stage: 4, sub: 1 },
  { id: 193, char: '爷爷', pinyin: 'yé ye',     meaning: 'grandfather (paternal)',     tone: 0, stage: 4, sub: 1 },
  { id: 194, char: '奶奶', pinyin: 'nǎi nai',   meaning: 'grandmother (paternal)',     tone: 0, stage: 4, sub: 1 },
  { id: 195, char: '外公', pinyin: 'wài gōng',  meaning: 'grandfather (maternal)',     tone: 0, stage: 4, sub: 1 },
  { id: 196, char: '外婆', pinyin: 'wài pó',    meaning: 'grandmother (maternal)',     tone: 0, stage: 4, sub: 1 },
  { id: 197, char: '丈夫', pinyin: 'zhàng fu',  meaning: 'husband',                    tone: 0, stage: 4, sub: 1 },
  { id: 198, char: '妻子', pinyin: 'qī zi',     meaning: 'wife',                       tone: 0, stage: 4, sub: 1 },
  { id: 199, char: '儿子', pinyin: 'ér zi',     meaning: 'son',                        tone: 0, stage: 4, sub: 1 },
  { id: 200, char: '女儿', pinyin: 'nǚ ér',     meaning: 'daughter',                   tone: 0, stage: 4, sub: 1 },

  { id: 201, char: '同事', pinyin: 'tóng shì',  meaning: 'colleague',                  tone: 0, stage: 4, sub: 2 },
  { id: 202, char: '同学', pinyin: 'tóng xué',  meaning: 'classmate',                  tone: 0, stage: 4, sub: 2 },
  { id: 203, char: '邻居', pinyin: 'lín jū',   meaning: 'neighbor',                   tone: 0, stage: 4, sub: 2 },
  { id: 204, char: '亲戚', pinyin: 'qīn qi',    meaning: 'relative',                   tone: 0, stage: 4, sub: 2 },
  { id: 205, char: '对象', pinyin: 'duì xiàng', meaning: 'boyfriend / girlfriend / partner', tone: 0, stage: 4, sub: 2 },
  { id: 206, char: '老板', pinyin: 'lǎo bǎn',   meaning: 'boss',                       tone: 0, stage: 4, sub: 2 },
  { id: 207, char: '伙伴', pinyin: 'huǒ bàn',   meaning: 'partner / companion',        tone: 0, stage: 4, sub: 2 },
  { id: 208, char: '客户', pinyin: 'kè hù',     meaning: 'client / customer',          tone: 0, stage: 4, sub: 2 },
  { id: 209, char: '保姆', pinyin: 'bǎo mǔ',    meaning: 'nanny / housekeeper',        tone: 0, stage: 4, sub: 2 },
  { id: 210, char: '恩人', pinyin: 'ēn rén',    meaning: 'benefactor',                 tone: 0, stage: 4, sub: 2 },

  { id: 211, char: '书', pinyin: 'shū',         meaning: 'book',                       tone: 1, stage: 4, sub: 3 },
  { id: 212, char: '笔', pinyin: 'bǐ',          meaning: 'pen',                        tone: 3, stage: 4, sub: 3 },
  { id: 213, char: '包', pinyin: 'bāo',         meaning: 'bag',                        tone: 1, stage: 4, sub: 3 },
  { id: 214, char: '本子', pinyin: 'běn zi',    meaning: 'notebook',                    tone: 0, stage: 4, sub: 3 },
  { id: 215, char: '钥匙', pinyin: 'yào shi',   meaning: 'key',                        tone: 0, stage: 4, sub: 3 },
  { id: 216, char: '钱包', pinyin: 'qián bāo',  meaning: 'wallet',                     tone: 0, stage: 4, sub: 3 },
  { id: 217, char: '眼镜', pinyin: 'yǎn jìng',  meaning: 'glasses',                    tone: 0, stage: 4, sub: 3 },
  { id: 218, char: '手机', pinyin: 'shǒu jī',   meaning: 'cellphone',                  tone: 0, stage: 4, sub: 3 },
  { id: 219, char: '电脑', pinyin: 'diàn nǎo',  meaning: 'computer',                   tone: 0, stage: 4, sub: 3 },
  { id: 220, char: '手表', pinyin: 'shǒu biǎo', meaning: 'wristwatch',                 tone: 0, stage: 4, sub: 3 },

  { id: 221, char: '中国', pinyin: 'zhōng guó', meaning: 'China',                      tone: 0, stage: 4, sub: 4 },
  { id: 222, char: '美国', pinyin: 'měi guó',   meaning: 'America',                    tone: 0, stage: 4, sub: 4 },
  { id: 223, char: '英国', pinyin: 'yīng guó',  meaning: 'United Kingdom',             tone: 0, stage: 4, sub: 4 },
  { id: 224, char: '法国', pinyin: 'fǎ guó',    meaning: 'France',                     tone: 0, stage: 4, sub: 4 },
  { id: 225, char: '日本', pinyin: 'rì běn',    meaning: 'Japan',                      tone: 0, stage: 4, sub: 4 },
  { id: 226, char: '韩国', pinyin: 'hán guó',   meaning: 'South Korea',                tone: 0, stage: 4, sub: 4 },
  { id: 227, char: '中文', pinyin: 'zhōng wén', meaning: 'Chinese language',           tone: 0, stage: 4, sub: 4 },
  { id: 228, char: '英文', pinyin: 'yīng wén',  meaning: 'English language',           tone: 0, stage: 4, sub: 4 },
  { id: 229, char: '语言', pinyin: 'yǔ yán',    meaning: 'language',                   tone: 0, stage: 4, sub: 4 },
  { id: 230, char: '国家', pinyin: 'guó jiā',   meaning: 'country',                    tone: 0, stage: 4, sub: 4 },

  { id: 231, char: '高', pinyin: 'gāo',         meaning: 'tall / high',                tone: 1, stage: 4, sub: 5 },
  { id: 232, char: '矮', pinyin: 'ǎi',          meaning: 'short (height)',             tone: 3, stage: 4, sub: 5 },
  { id: 233, char: '胖', pinyin: 'pàng',        meaning: 'fat / plump',                tone: 4, stage: 4, sub: 5 },
  { id: 234, char: '瘦', pinyin: 'shòu',        meaning: 'thin / slim',                tone: 4, stage: 4, sub: 5 },
  { id: 235, char: '漂亮', pinyin: 'piào liang',meaning: 'beautiful',                  tone: 0, stage: 4, sub: 5 },
  { id: 236, char: '帅', pinyin: 'shuài',       meaning: 'handsome',                   tone: 4, stage: 4, sub: 5 },
  { id: 237, char: '聪明', pinyin: 'cōng míng', meaning: 'smart / clever',             tone: 0, stage: 4, sub: 5 },
  { id: 238, char: '可爱', pinyin: 'kě ài',     meaning: 'cute / lovable',             tone: 0, stage: 4, sub: 5 },
  { id: 239, char: '努力', pinyin: 'nǔ lì',     meaning: 'hardworking / diligent',     tone: 0, stage: 4, sub: 5 },
  { id: 240, char: '友好', pinyin: 'yǒu hǎo',   meaning: 'friendly',                   tone: 0, stage: 4, sub: 5 },

  // Stage 5 — Food & Dining
  { id: 241, char: '菜', pinyin: 'cài',         meaning: 'dish / vegetable',           tone: 4, stage: 5, sub: 0 },
  { id: 242, char: '饭', pinyin: 'fàn',         meaning: 'cooked rice / meal',         tone: 4, stage: 5, sub: 0 },
  { id: 243, char: '饺子', pinyin: 'jiǎo zi',   meaning: 'dumplings',                  tone: 0, stage: 5, sub: 0 },
  { id: 244, char: '包子', pinyin: 'bāo zi',    meaning: 'steamed buns',               tone: 0, stage: 5, sub: 0 },
  { id: 245, char: '炒饭', pinyin: 'chǎo fàn',  meaning: 'fried rice',                 tone: 0, stage: 5, sub: 0 },
  { id: 246, char: '汤', pinyin: 'tāng',        meaning: 'soup',                       tone: 1, stage: 5, sub: 0 },
  { id: 247, char: '沙拉', pinyin: 'shā lā',    meaning: 'salad',                      tone: 0, stage: 5, sub: 0 },
  { id: 248, char: '三明治', pinyin: 'sān míng zhì', meaning: 'sandwich',              tone: 0, stage: 5, sub: 0 },
  { id: 249, char: '披萨', pinyin: 'pī sà',     meaning: 'pizza',                      tone: 0, stage: 5, sub: 0 },
  { id: 250, char: '汉堡', pinyin: 'hàn bǎo',   meaning: 'hamburger',                  tone: 0, stage: 5, sub: 0 },

  { id: 251, char: '苹果', pinyin: 'píng guǒ',  meaning: 'apple',                      tone: 0, stage: 5, sub: 1 },
  { id: 252, char: '香蕉', pinyin: 'xiāng jiāo',meaning: 'banana',                     tone: 0, stage: 5, sub: 1 },
  { id: 253, char: '橙子', pinyin: 'chéng zi',  meaning: 'orange',                     tone: 0, stage: 5, sub: 1 },
  { id: 254, char: '西瓜', pinyin: 'xī guā',    meaning: 'watermelon',                 tone: 0, stage: 5, sub: 1 },
  { id: 255, char: '葡萄', pinyin: 'pú tao',    meaning: 'grape',                      tone: 0, stage: 5, sub: 1 },
  { id: 256, char: '蔬菜', pinyin: 'shū cài',   meaning: 'vegetables',                 tone: 0, stage: 5, sub: 1 },
  { id: 257, char: '白菜', pinyin: 'bái cài',   meaning: 'Chinese cabbage',            tone: 0, stage: 5, sub: 1 },
  { id: 258, char: '土豆', pinyin: 'tǔ dòu',    meaning: 'potato',                     tone: 0, stage: 5, sub: 1 },
  { id: 259, char: '番茄', pinyin: 'fān qié',   meaning: 'tomato',                     tone: 0, stage: 5, sub: 1 },
  { id: 260, char: '玉米', pinyin: 'yù mǐ',     meaning: 'corn',                       tone: 0, stage: 5, sub: 1 },

  { id: 261, char: '牛肉', pinyin: 'niú ròu',   meaning: 'beef',                       tone: 0, stage: 5, sub: 2 },
  { id: 262, char: '猪肉', pinyin: 'zhū ròu',   meaning: 'pork',                       tone: 0, stage: 5, sub: 2 },
  { id: 263, char: '鸡肉', pinyin: 'jī ròu',    meaning: 'chicken (meat)',             tone: 0, stage: 5, sub: 2 },
  { id: 264, char: '羊肉', pinyin: 'yáng ròu',  meaning: 'lamb',                       tone: 0, stage: 5, sub: 2 },
  { id: 265, char: '虾', pinyin: 'xiā',         meaning: 'shrimp',                     tone: 1, stage: 5, sub: 2 },
  { id: 266, char: '鸡蛋', pinyin: 'jī dàn',    meaning: 'egg',                        tone: 0, stage: 5, sub: 2 },
  { id: 267, char: '豆腐', pinyin: 'dòu fu',    meaning: 'tofu',                       tone: 0, stage: 5, sub: 2 },
  { id: 268, char: '海鲜', pinyin: 'hǎi xiān',  meaning: 'seafood',                    tone: 0, stage: 5, sub: 2 },
  { id: 269, char: '辣', pinyin: 'là',          meaning: 'spicy',                      tone: 4, stage: 5, sub: 2 },
  { id: 270, char: '盐', pinyin: 'yán',         meaning: 'salt',                       tone: 2, stage: 5, sub: 2 },

  { id: 271, char: '炒', pinyin: 'chǎo',        meaning: 'stir-fry',                   tone: 3, stage: 5, sub: 3 },
  { id: 272, char: '蒸', pinyin: 'zhēng',       meaning: 'steam',                      tone: 1, stage: 5, sub: 3 },
  { id: 273, char: '煮', pinyin: 'zhǔ',         meaning: 'boil',                       tone: 3, stage: 5, sub: 3 },
  { id: 274, char: '烤', pinyin: 'kǎo',         meaning: 'roast / grill',              tone: 3, stage: 5, sub: 3 },
  { id: 275, char: '炸', pinyin: 'zhá',         meaning: 'deep-fry',                   tone: 2, stage: 5, sub: 3 },
  { id: 276, char: '煎', pinyin: 'jiān',        meaning: 'pan-fry',                    tone: 1, stage: 5, sub: 3 },
  { id: 277, char: '凉', pinyin: 'liáng',       meaning: 'cool / cold (food)',         tone: 2, stage: 5, sub: 3 },
  { id: 278, char: '热', pinyin: 'rè',          meaning: 'hot',                        tone: 4, stage: 5, sub: 3 },
  { id: 279, char: '新鲜', pinyin: 'xīn xiān',  meaning: 'fresh',                      tone: 0, stage: 5, sub: 3 },
  { id: 280, char: '味道', pinyin: 'wèi dao',   meaning: 'flavor / taste',             tone: 0, stage: 5, sub: 3 },

  { id: 281, char: '菜单', pinyin: 'cài dān',   meaning: 'menu',                       tone: 0, stage: 5, sub: 4 },
  { id: 282, char: '点菜', pinyin: 'diǎn cài',  meaning: 'to order food',              tone: 0, stage: 5, sub: 4 },
  { id: 283, char: '买单', pinyin: 'mǎi dān',   meaning: 'to pay the bill',            tone: 0, stage: 5, sub: 4 },
  { id: 284, char: '打包', pinyin: 'dǎ bāo',    meaning: 'to takeaway / doggie bag',   tone: 0, stage: 5, sub: 4 },
  { id: 285, char: '筷子', pinyin: 'kuài zi',   meaning: 'chopsticks',                 tone: 0, stage: 5, sub: 4 },
  { id: 286, char: '碗', pinyin: 'wǎn',         meaning: 'bowl',                       tone: 3, stage: 5, sub: 4 },
  { id: 287, char: '盘子', pinyin: 'pán zi',    meaning: 'plate',                      tone: 0, stage: 5, sub: 4 },
  { id: 288, char: '杯子', pinyin: 'bēi zi',    meaning: 'cup / glass',                tone: 0, stage: 5, sub: 4 },
  { id: 289, char: '服务员', pinyin: 'fú wù yuán', meaning: 'waiter / server',          tone: 0, stage: 5, sub: 4 },
  { id: 290, char: '小费', pinyin: 'xiǎo fèi',  meaning: 'tip / gratuity',             tone: 0, stage: 5, sub: 4 },

  { id: 291, char: '果汁', pinyin: 'guǒ zhī',   meaning: 'fruit juice',                tone: 0, stage: 5, sub: 5 },
  { id: 292, char: '可乐', pinyin: 'kě lè',     meaning: 'cola',                       tone: 0, stage: 5, sub: 5 },
  { id: 293, char: '酒', pinyin: 'jiǔ',         meaning: 'alcohol / liquor',           tone: 3, stage: 5, sub: 5 },
  { id: 294, char: '酸奶', pinyin: 'suān nǎi',  meaning: 'yogurt',                     tone: 0, stage: 5, sub: 5 },
  { id: 295, char: '冰', pinyin: 'bīng',        meaning: 'ice',                        tone: 1, stage: 5, sub: 5 },
  { id: 296, char: '糖', pinyin: 'táng',        meaning: 'sugar / sweets',             tone: 2, stage: 5, sub: 5 },
  { id: 297, char: '瓶', pinyin: 'píng',        meaning: 'bottle',                     tone: 2, stage: 5, sub: 5 },
  { id: 298, char: '热水', pinyin: 'rè shuǐ',   meaning: 'hot water',                  tone: 0, stage: 5, sub: 5 },
  { id: 299, char: '冷水', pinyin: 'lěng shuǐ', meaning: 'cold water',                 tone: 0, stage: 5, sub: 5 },
  { id: 300, char: '饮料', pinyin: 'yǐn liào',  meaning: 'beverage',                   tone: 0, stage: 5, sub: 5 },

  // Stage 6 — Getting Around
  { id: 301, char: '公共汽车', pinyin: 'gōng gòng qì chē', meaning: 'bus',            tone: 0, stage: 6, sub: 0 },
  { id: 302, char: '地铁', pinyin: 'dì tiě',   meaning: 'subway / metro',              tone: 0, stage: 6, sub: 0 },
  { id: 303, char: '出租车', pinyin: 'chū zū chē', meaning: 'taxi',                    tone: 0, stage: 6, sub: 0 },
  { id: 304, char: '自行车', pinyin: 'zì xíng chē', meaning: 'bicycle',                tone: 0, stage: 6, sub: 0 },
  { id: 305, char: '飞机', pinyin: 'fēi jī',   meaning: 'airplane',                    tone: 0, stage: 6, sub: 0 },
  { id: 306, char: '火车', pinyin: 'huǒ chē',   meaning: 'train',                      tone: 0, stage: 6, sub: 0 },
  { id: 307, char: '船', pinyin: 'chuán',       meaning: 'boat / ship',                tone: 2, stage: 6, sub: 0 },
  { id: 308, char: '走路', pinyin: 'zǒu lù',    meaning: 'to walk',                    tone: 0, stage: 6, sub: 0 },
  { id: 309, char: '开车', pinyin: 'kāi chē',   meaning: 'to drive',                   tone: 0, stage: 6, sub: 0 },
  { id: 310, char: '骑车', pinyin: 'qí chē',    meaning: 'to ride a bike',             tone: 0, stage: 6, sub: 0 },

  { id: 311, char: '左', pinyin: 'zuǒ',         meaning: 'left',                       tone: 3, stage: 6, sub: 1 },
  { id: 312, char: '右', pinyin: 'yòu',         meaning: 'right',                      tone: 4, stage: 6, sub: 1 },
  { id: 313, char: '北', pinyin: 'běi',         meaning: 'north',                      tone: 3, stage: 6, sub: 1 },
  { id: 314, char: '南', pinyin: 'nán',         meaning: 'south',                      tone: 2, stage: 6, sub: 1 },
  { id: 315, char: '东', pinyin: 'dōng',        meaning: 'east',                       tone: 1, stage: 6, sub: 1 },
  { id: 316, char: '西', pinyin: 'xī',          meaning: 'west',                       tone: 1, stage: 6, sub: 1 },
  { id: 317, char: '前', pinyin: 'qián',        meaning: 'front / before',             tone: 2, stage: 6, sub: 1 },
  { id: 318, char: '后', pinyin: 'hòu',         meaning: 'behind / after',             tone: 4, stage: 6, sub: 1 },
  { id: 319, char: '直', pinyin: 'zhí',         meaning: 'straight',                   tone: 2, stage: 6, sub: 1 },
  { id: 320, char: '方向', pinyin: 'fāng xiàng',meaning: 'direction',                  tone: 0, stage: 6, sub: 1 },

  { id: 321, char: '上面', pinyin: 'shàng miàn',meaning: 'on top / above',             tone: 0, stage: 6, sub: 2 },
  { id: 322, char: '下面', pinyin: 'xià miàn',  meaning: 'below / under',              tone: 0, stage: 6, sub: 2 },
  { id: 323, char: '里面', pinyin: 'lǐ miàn',   meaning: 'inside',                     tone: 0, stage: 6, sub: 2 },
  { id: 324, char: '外面', pinyin: 'wài miàn',  meaning: 'outside',                    tone: 0, stage: 6, sub: 2 },
  { id: 325, char: '旁边', pinyin: 'páng biān', meaning: 'beside / next to',           tone: 0, stage: 6, sub: 2 },
  { id: 326, char: '对面', pinyin: 'duì miàn',  meaning: 'across from',                tone: 0, stage: 6, sub: 2 },
  { id: 327, char: '中间', pinyin: 'zhōng jiān',meaning: 'middle / center',            tone: 0, stage: 6, sub: 2 },
  { id: 328, char: '前面', pinyin: 'qián miàn', meaning: 'in front',                   tone: 0, stage: 6, sub: 2 },
  { id: 329, char: '后面', pinyin: 'hòu miàn',  meaning: 'behind',                     tone: 0, stage: 6, sub: 2 },
  { id: 330, char: '附近', pinyin: 'fù jìn',    meaning: 'nearby',                     tone: 0, stage: 6, sub: 2 },

  { id: 331, char: '机场', pinyin: 'jī chǎng',  meaning: 'airport',                    tone: 0, stage: 6, sub: 3 },
  { id: 332, char: '火车站', pinyin: 'huǒ chē zhàn', meaning: 'train station',          tone: 0, stage: 6, sub: 3 },
  { id: 333, char: '银行', pinyin: 'yín háng',  meaning: 'bank',                       tone: 0, stage: 6, sub: 3 },
  { id: 334, char: '学校', pinyin: 'xué xiào',  meaning: 'school',                     tone: 0, stage: 6, sub: 3 },
  { id: 335, char: '邮局', pinyin: 'yóu jú',    meaning: 'post office',                tone: 0, stage: 6, sub: 3 },
  { id: 336, char: '图书馆', pinyin: 'tú shū guǎn', meaning: 'library',                tone: 0, stage: 6, sub: 3 },
  { id: 337, char: '公园', pinyin: 'gōng yuán', meaning: 'park',                       tone: 0, stage: 6, sub: 3 },
  { id: 338, char: '超市', pinyin: 'chāo shì',  meaning: 'supermarket',                tone: 0, stage: 6, sub: 3 },
  { id: 339, char: '餐厅', pinyin: 'cān tīng',  meaning: 'restaurant',                 tone: 0, stage: 6, sub: 3 },
  { id: 340, char: '厕所', pinyin: 'cè suǒ',    meaning: 'toilet / restroom',          tone: 0, stage: 6, sub: 3 },

  { id: 341, char: '票', pinyin: 'piào',        meaning: 'ticket',                     tone: 4, stage: 6, sub: 4 },
  { id: 342, char: '站', pinyin: 'zhàn',        meaning: 'station / stop',             tone: 4, stage: 6, sub: 4 },
  { id: 343, char: '换乘', pinyin: 'huàn chéng',meaning: 'to transfer',                tone: 0, stage: 6, sub: 4 },
  { id: 344, char: '下车', pinyin: 'xià chē',   meaning: 'to get off',                 tone: 0, stage: 6, sub: 4 },
  { id: 345, char: '上车', pinyin: 'shàng chē', meaning: 'to get on',                  tone: 0, stage: 6, sub: 4 },
  { id: 346, char: '出口', pinyin: 'chū kǒu',   meaning: 'exit',                       tone: 0, stage: 6, sub: 4 },
  { id: 347, char: '入口', pinyin: 'rù kǒu',    meaning: 'entrance',                   tone: 0, stage: 6, sub: 4 },
  { id: 348, char: '单程', pinyin: 'dān chéng', meaning: 'one-way',                    tone: 0, stage: 6, sub: 4 },
  { id: 349, char: '往返', pinyin: 'wǎng fǎn',  meaning: 'round trip',                 tone: 0, stage: 6, sub: 4 },
  { id: 350, char: '价格', pinyin: 'jià gé',    meaning: 'price',                      tone: 0, stage: 6, sub: 4 },

  { id: 351, char: '路', pinyin: 'lù',          meaning: 'road',                       tone: 4, stage: 6, sub: 5 },
  { id: 352, char: '街', pinyin: 'jiē',         meaning: 'street',                     tone: 1, stage: 6, sub: 5 },
  { id: 353, char: '红绿灯', pinyin: 'hóng lǜ dēng', meaning: 'traffic light',         tone: 0, stage: 6, sub: 5 },
  { id: 354, char: '路口', pinyin: 'lù kǒu',    meaning: 'intersection',               tone: 0, stage: 6, sub: 5 },
  { id: 355, char: '堵车', pinyin: 'dǔ chē',    meaning: 'traffic jam',                tone: 0, stage: 6, sub: 5 },
  { id: 356, char: '桥', pinyin: 'qiáo',        meaning: 'bridge',                     tone: 2, stage: 6, sub: 5 },
  { id: 357, char: '高速', pinyin: 'gāo sù',    meaning: 'highway',                    tone: 0, stage: 6, sub: 5 },
  { id: 358, char: '停车场', pinyin: 'tíng chē chǎng', meaning: 'parking lot',         tone: 0, stage: 6, sub: 5 },
  { id: 359, char: '加油站', pinyin: 'jiā yóu zhàn', meaning: 'gas station',           tone: 0, stage: 6, sub: 5 },
  { id: 360, char: '地图', pinyin: 'dì tú',     meaning: 'map',                        tone: 0, stage: 6, sub: 5 },

  // --- Phase 3: Daily Life ---

  // Stage 7 — Shopping & Money
  { id: 361, char: '衣服', pinyin: 'yī fu',     meaning: 'clothes',                    tone: 0, stage: 7, sub: 0 },
  { id: 362, char: '衬衫', pinyin: 'chèn shān', meaning: 'shirt',                      tone: 0, stage: 7, sub: 0 },
  { id: 363, char: '裤子', pinyin: 'kù zi',     meaning: 'pants / trousers',           tone: 0, stage: 7, sub: 0 },
  { id: 364, char: '鞋', pinyin: 'xié',         meaning: 'shoes',                      tone: 2, stage: 7, sub: 0 },
  { id: 365, char: '帽子', pinyin: 'mào zi',    meaning: 'hat',                        tone: 0, stage: 7, sub: 0 },
  { id: 366, char: '袜子', pinyin: 'wà zi',     meaning: 'socks',                      tone: 0, stage: 7, sub: 0 },
  { id: 367, char: '手套', pinyin: 'shǒu tào',  meaning: 'gloves',                     tone: 0, stage: 7, sub: 0 },
  { id: 368, char: '领带', pinyin: 'lǐng dài',  meaning: 'necktie',                    tone: 0, stage: 7, sub: 0 },
  { id: 369, char: '围巾', pinyin: 'wéi jīn',   meaning: 'scarf',                      tone: 0, stage: 7, sub: 0 },
  { id: 370, char: '项链', pinyin: 'xiàng liàn',meaning: 'necklace',                   tone: 0, stage: 7, sub: 0 },

  { id: 371, char: '颜色', pinyin: 'yán sè',    meaning: 'color',                      tone: 0, stage: 7, sub: 1 },
  { id: 372, char: '红', pinyin: 'hóng',        meaning: 'red',                        tone: 2, stage: 7, sub: 1 },
  { id: 373, char: '蓝', pinyin: 'lán',         meaning: 'blue',                       tone: 2, stage: 7, sub: 1 },
  { id: 374, char: '黄', pinyin: 'huáng',       meaning: 'yellow',                     tone: 2, stage: 7, sub: 1 },
  { id: 375, char: '黑', pinyin: 'hēi',         meaning: 'black',                      tone: 1, stage: 7, sub: 1 },
  { id: 376, char: '白', pinyin: 'bái',         meaning: 'white',                      tone: 2, stage: 7, sub: 1 },
  { id: 377, char: '灰', pinyin: 'huī',         meaning: 'gray',                       tone: 1, stage: 7, sub: 1 },
  { id: 378, char: '紫', pinyin: 'zǐ',          meaning: 'purple',                     tone: 3, stage: 7, sub: 1 },
  { id: 379, char: '金', pinyin: 'jīn',         meaning: 'gold / golden',              tone: 1, stage: 7, sub: 1 },
  { id: 380, char: '银', pinyin: 'yín',         meaning: 'silver',                     tone: 2, stage: 7, sub: 1 },

  { id: 381, char: '便宜', pinyin: 'pián yi',   meaning: 'cheap',                      tone: 0, stage: 7, sub: 2 },
  { id: 382, char: '打折', pinyin: 'dǎ zhé',    meaning: 'discount / on sale',         tone: 0, stage: 7, sub: 2 },
  { id: 383, char: '现金', pinyin: 'xiàn jīn',  meaning: 'cash',                       tone: 0, stage: 7, sub: 2 },
  { id: 384, char: '刷卡', pinyin: 'shuā kǎ',   meaning: 'to pay by card',             tone: 0, stage: 7, sub: 2 },
  { id: 385, char: '收据', pinyin: 'shōu jù',   meaning: 'receipt',                    tone: 0, stage: 7, sub: 2 },
  { id: 386, char: '发票', pinyin: 'fā piào',   meaning: 'invoice',                    tone: 0, stage: 7, sub: 2 },
  { id: 387, char: '免费', pinyin: 'miǎn fèi',  meaning: 'free of charge',             tone: 0, stage: 7, sub: 2 },
  { id: 388, char: '划算', pinyin: 'huá suàn',  meaning: 'cost-effective / good deal', tone: 0, stage: 7, sub: 2 },
  { id: 389, char: '最低', pinyin: 'zuì dī',    meaning: 'lowest / minimum',           tone: 0, stage: 7, sub: 2 },
  { id: 390, char: '报价', pinyin: 'bào jià',   meaning: 'quoted price',               tone: 0, stage: 7, sub: 2 },

  { id: 391, char: '商场', pinyin: 'shāng chǎng', meaning: 'shopping mall',            tone: 0, stage: 7, sub: 3 },
  { id: 392, char: '集市', pinyin: 'jí shì',    meaning: 'market / fair',              tone: 0, stage: 7, sub: 3 },
  { id: 393, char: '市场', pinyin: 'shì chǎng', meaning: 'market',                     tone: 0, stage: 7, sub: 3 },
  { id: 394, char: '商店', pinyin: 'shāng diàn',meaning: 'store / shop',               tone: 0, stage: 7, sub: 3 },
  { id: 395, char: '网上', pinyin: 'wǎng shàng',meaning: 'online',                     tone: 0, stage: 7, sub: 3 },
  { id: 396, char: '购物', pinyin: 'gòu wù',    meaning: 'shopping',                   tone: 0, stage: 7, sub: 3 },
  { id: 397, char: '牌子', pinyin: 'pái zi',    meaning: 'brand',                      tone: 0, stage: 7, sub: 3 },
  { id: 398, char: '款式', pinyin: 'kuǎn shì',  meaning: 'style / design',             tone: 0, stage: 7, sub: 3 },
  { id: 399, char: '样品', pinyin: 'yàng pǐn',  meaning: 'sample',                     tone: 0, stage: 7, sub: 3 },
  { id: 400, char: '订单', pinyin: 'dìng dān',  meaning: 'order (placed order)',       tone: 0, stage: 7, sub: 3 },

  { id: 401, char: '微信', pinyin: 'wēi xìn',   meaning: 'WeChat',                     tone: 0, stage: 7, sub: 4 },
  { id: 402, char: '支付', pinyin: 'zhī fù',    meaning: 'payment',                    tone: 0, stage: 7, sub: 4 },
  { id: 403, char: '支付宝', pinyin: 'zhī fù bǎo', meaning: 'Alipay',                  tone: 0, stage: 7, sub: 4 },
  { id: 404, char: '扫码', pinyin: 'sǎo mǎ',    meaning: 'scan QR code',               tone: 0, stage: 7, sub: 4 },
  { id: 405, char: '转账', pinyin: 'zhuǎn zhàng',meaning: 'transfer money',             tone: 0, stage: 7, sub: 4 },
  { id: 406, char: '红包', pinyin: 'hóng bāo',  meaning: 'red envelope',               tone: 0, stage: 7, sub: 4 },
  { id: 407, char: '余额', pinyin: 'yú é',      meaning: 'balance',                    tone: 0, stage: 7, sub: 4 },
  { id: 408, char: '密码', pinyin: 'mì mǎ',     meaning: 'password / PIN',             tone: 0, stage: 7, sub: 4 },
  { id: 409, char: '账户', pinyin: 'zhàng hù',  meaning: 'account',                    tone: 0, stage: 7, sub: 4 },
  { id: 410, char: '安全', pinyin: 'ān quán',   meaning: 'security / safe',            tone: 0, stage: 7, sub: 4 },

  { id: 411, char: '退货', pinyin: 'tuì huò',   meaning: 'return goods',               tone: 0, stage: 7, sub: 5 },
  { id: 412, char: '换货', pinyin: 'huàn huò',  meaning: 'exchange goods',             tone: 0, stage: 7, sub: 5 },
  { id: 413, char: '质量', pinyin: 'zhì liàng', meaning: 'quality',                    tone: 0, stage: 7, sub: 5 },
  { id: 414, char: '毛病', pinyin: 'máo bìng',  meaning: 'fault / defect',             tone: 0, stage: 7, sub: 5 },
  { id: 415, char: '保修', pinyin: 'bǎo xiū',   meaning: 'warranty',                   tone: 0, stage: 7, sub: 5 },
  { id: 416, char: '快递', pinyin: 'kuài dì',   meaning: 'express delivery',           tone: 0, stage: 7, sub: 5 },
  { id: 417, char: '包装', pinyin: 'bāo zhuāng',meaning: 'packaging',                  tone: 0, stage: 7, sub: 5 },
  { id: 418, char: '客服', pinyin: 'kè fú',     meaning: 'customer service',           tone: 0, stage: 7, sub: 5 },
  { id: 419, char: '投诉', pinyin: 'tóu sù',    meaning: 'complaint / to complain',    tone: 0, stage: 7, sub: 5 },
  { id: 420, char: '退款', pinyin: 'tuì kuǎn',  meaning: 'refund',                     tone: 0, stage: 7, sub: 5 },

  // Stage 8 — Home & Routine
  { id: 421, char: '房间', pinyin: 'fáng jiān', meaning: 'room',                       tone: 0, stage: 8, sub: 0 },
  { id: 422, char: '卧室', pinyin: 'wò shì',    meaning: 'bedroom',                    tone: 0, stage: 8, sub: 0 },
  { id: 423, char: '厨房', pinyin: 'chú fáng',  meaning: 'kitchen',                    tone: 0, stage: 8, sub: 0 },
  { id: 424, char: '浴室', pinyin: 'yù shì',    meaning: 'bathroom',                   tone: 0, stage: 8, sub: 0 },
  { id: 425, char: '客厅', pinyin: 'kè tīng',   meaning: 'living room',                tone: 0, stage: 8, sub: 0 },
  { id: 426, char: '沙发', pinyin: 'shā fā',    meaning: 'sofa',                       tone: 0, stage: 8, sub: 0 },
  { id: 427, char: '桌子', pinyin: 'zhuō zi',   meaning: 'table',                      tone: 0, stage: 8, sub: 0 },
  { id: 428, char: '椅子', pinyin: 'yǐ zi',     meaning: 'chair',                      tone: 0, stage: 8, sub: 0 },
  { id: 429, char: '床', pinyin: 'chuáng',      meaning: 'bed',                        tone: 2, stage: 8, sub: 0 },
  { id: 430, char: '门', pinyin: 'mén',         meaning: 'door',                       tone: 2, stage: 8, sub: 0 },

  { id: 431, char: '电视', pinyin: 'diàn shì',  meaning: 'television',                 tone: 0, stage: 8, sub: 1 },
  { id: 432, char: '冰箱', pinyin: 'bīng xiāng',meaning: 'refrigerator',                tone: 0, stage: 8, sub: 1 },
  { id: 433, char: '空调', pinyin: 'kōng tiáo', meaning: 'air conditioner',             tone: 0, stage: 8, sub: 1 },
  { id: 434, char: '洗衣机', pinyin: 'xǐ yī jī',meaning: 'washing machine',             tone: 0, stage: 8, sub: 1 },
  { id: 435, char: '灯', pinyin: 'dēng',        meaning: 'lamp / light',               tone: 1, stage: 8, sub: 1 },
  { id: 436, char: '窗户', pinyin: 'chuāng hu', meaning: 'window',                     tone: 0, stage: 8, sub: 1 },
  { id: 437, char: '墙', pinyin: 'qiáng',       meaning: 'wall',                       tone: 2, stage: 8, sub: 1 },
  { id: 438, char: '地板', pinyin: 'dì bǎn',    meaning: 'floor',                      tone: 0, stage: 8, sub: 1 },
  { id: 439, char: '垃圾', pinyin: 'lā jī',     meaning: 'trash / garbage',            tone: 0, stage: 8, sub: 1 },
  { id: 440, char: '钟', pinyin: 'zhōng',       meaning: 'clock',                      tone: 1, stage: 8, sub: 1 },

  { id: 441, char: '起床', pinyin: 'qǐ chuáng', meaning: 'to get up',                  tone: 0, stage: 8, sub: 2 },
  { id: 442, char: '上班', pinyin: 'shàng bān', meaning: 'to go to work',              tone: 0, stage: 8, sub: 2 },
  { id: 443, char: '下班', pinyin: 'xià bān',   meaning: 'to get off work',            tone: 0, stage: 8, sub: 2 },
  { id: 444, char: '睡觉', pinyin: 'shuì jiào', meaning: 'to sleep',                   tone: 0, stage: 8, sub: 2 },
  { id: 445, char: '休息', pinyin: 'xiū xi',    meaning: 'to rest',                    tone: 0, stage: 8, sub: 2 },
  { id: 446, char: '洗澡', pinyin: 'xǐ zǎo',    meaning: 'to take a shower / bath',    tone: 0, stage: 8, sub: 2 },
  { id: 447, char: '穿衣', pinyin: 'chuān yī',  meaning: 'to get dressed',             tone: 0, stage: 8, sub: 2 },
  { id: 448, char: '刷牙', pinyin: 'shuā yá',   meaning: 'to brush teeth',             tone: 0, stage: 8, sub: 2 },
  { id: 449, char: '洗脸', pinyin: 'xǐ liǎn',   meaning: 'to wash face',               tone: 0, stage: 8, sub: 2 },
  { id: 450, char: '出门', pinyin: 'chū mén',   meaning: 'to go out / leave home',     tone: 0, stage: 8, sub: 2 },

  { id: 451, char: '每天', pinyin: 'měi tiān',  meaning: 'every day',                  tone: 0, stage: 8, sub: 3 },
  { id: 452, char: '有时候', pinyin: 'yǒu shí hou', meaning: 'sometimes',               tone: 0, stage: 8, sub: 3 },
  { id: 453, char: '经常', pinyin: 'jīng cháng',meaning: 'often',                      tone: 0, stage: 8, sub: 3 },
  { id: 454, char: '从不', pinyin: 'cóng bù',   meaning: 'never',                      tone: 0, stage: 8, sub: 3 },
  { id: 455, char: '总是', pinyin: 'zǒng shì',  meaning: 'always',                     tone: 0, stage: 8, sub: 3 },
  { id: 456, char: '很少', pinyin: 'hěn shǎo',  meaning: 'rarely',                     tone: 0, stage: 8, sub: 3 },
  { id: 457, char: '偶尔', pinyin: 'ǒu ěr',     meaning: 'occasionally',               tone: 0, stage: 8, sub: 3 },
  { id: 458, char: '一直', pinyin: 'yī zhí',    meaning: 'always / continuously',      tone: 0, stage: 8, sub: 3 },
  { id: 459, char: '再次', pinyin: 'zài cì',    meaning: 'again',                      tone: 0, stage: 8, sub: 3 },
  { id: 460, char: '每次', pinyin: 'měi cì',    meaning: 'every time',                 tone: 0, stage: 8, sub: 3 },

  { id: 461, char: '租房', pinyin: 'zū fáng',   meaning: 'to rent a house',            tone: 0, stage: 8, sub: 4 },
  { id: 462, char: '房东', pinyin: 'fáng dōng', meaning: 'landlord / landlady',        tone: 0, stage: 8, sub: 4 },
  { id: 463, char: '房租', pinyin: 'fáng zū',   meaning: 'rent (payment)',             tone: 0, stage: 8, sub: 4 },
  { id: 464, char: '押金', pinyin: 'yā jīn',    meaning: 'deposit',                    tone: 0, stage: 8, sub: 4 },
  { id: 465, char: '水电', pinyin: 'shuǐ diàn', meaning: 'water & electricity',        tone: 0, stage: 8, sub: 4 },
  { id: 466, char: '合同', pinyin: 'hé tong',   meaning: 'contract',                   tone: 0, stage: 8, sub: 4 },
  { id: 467, char: '搬家', pinyin: 'bān jiā',   meaning: 'to move house',              tone: 0, stage: 8, sub: 4 },
  { id: 468, char: '装修', pinyin: 'zhuāng xiū',meaning: 'to renovate / decoration',   tone: 0, stage: 8, sub: 4 },
  { id: 469, char: '物业', pinyin: 'wù yè',     meaning: 'property management',        tone: 0, stage: 8, sub: 4 },
  { id: 470, char: '家具', pinyin: 'jiā jù',    meaning: 'furniture',                  tone: 0, stage: 8, sub: 4 },

  { id: 471, char: '打扫', pinyin: 'dǎ sǎo',    meaning: 'to clean',                   tone: 0, stage: 8, sub: 5 },
  { id: 472, char: '做饭', pinyin: 'zuò fàn',   meaning: 'to cook (a meal)',           tone: 0, stage: 8, sub: 5 },
  { id: 473, char: '洗碗', pinyin: 'xǐ wǎn',    meaning: 'to wash dishes',             tone: 0, stage: 8, sub: 5 },
  { id: 474, char: '洗衣', pinyin: 'xǐ yī',     meaning: 'to do laundry',              tone: 0, stage: 8, sub: 5 },
  { id: 475, char: '买菜', pinyin: 'mǎi cài',   meaning: 'to buy groceries',           tone: 0, stage: 8, sub: 5 },
  { id: 476, char: '整理', pinyin: 'zhěng lǐ',  meaning: 'to tidy up',                 tone: 0, stage: 8, sub: 5 },
  { id: 477, char: '倒垃圾', pinyin: 'dào lā jī', meaning: 'to take out the trash',    tone: 0, stage: 8, sub: 5 },
  { id: 478, char: '擦桌子', pinyin: 'cā zhuō zi', meaning: 'to wipe the table',       tone: 0, stage: 8, sub: 5 },
  { id: 479, char: '铺床', pinyin: 'pū chuáng', meaning: 'to make the bed',            tone: 0, stage: 8, sub: 5 },
  { id: 480, char: '遛狗', pinyin: 'liù gǒu',   meaning: 'to walk the dog',            tone: 0, stage: 8, sub: 5 },

  // Stage 9 — Health & Body
  { id: 481, char: '头', pinyin: 'tóu',         meaning: 'head',                       tone: 2, stage: 9, sub: 0 },
  { id: 482, char: '手', pinyin: 'shǒu',        meaning: 'hand',                       tone: 3, stage: 9, sub: 0 },
  { id: 483, char: '脚', pinyin: 'jiǎo',        meaning: 'foot',                       tone: 3, stage: 9, sub: 0 },
  { id: 484, char: '腿', pinyin: 'tuǐ',         meaning: 'leg',                        tone: 3, stage: 9, sub: 0 },
  { id: 485, char: '胳膊', pinyin: 'gē bo',     meaning: 'arm',                        tone: 0, stage: 9, sub: 0 },
  { id: 486, char: '肚子', pinyin: 'dù zi',     meaning: 'belly / stomach',            tone: 0, stage: 9, sub: 0 },
  { id: 487, char: '眼睛', pinyin: 'yǎn jīng',  meaning: 'eye',                        tone: 0, stage: 9, sub: 0 },
  { id: 488, char: '耳朵', pinyin: 'ěr duo',    meaning: 'ear',                        tone: 0, stage: 9, sub: 0 },
  { id: 489, char: '嘴', pinyin: 'zuǐ',         meaning: 'mouth',                      tone: 3, stage: 9, sub: 0 },
  { id: 490, char: '鼻子', pinyin: 'bí zi',     meaning: 'nose',                       tone: 0, stage: 9, sub: 0 },

  { id: 491, char: '发烧', pinyin: 'fā shāo',   meaning: 'to have a fever',            tone: 0, stage: 9, sub: 1 },
  { id: 492, char: '咳嗽', pinyin: 'ké sou',    meaning: 'to cough',                   tone: 0, stage: 9, sub: 1 },
  { id: 493, char: '头痛', pinyin: 'tóu tòng',  meaning: 'headache',                   tone: 0, stage: 9, sub: 1 },
  { id: 494, char: '感冒', pinyin: 'gǎn mào',   meaning: 'cold / flu',                 tone: 0, stage: 9, sub: 1 },
  { id: 495, char: '牙疼', pinyin: 'yá téng',   meaning: 'toothache',                  tone: 0, stage: 9, sub: 1 },
  { id: 496, char: '头晕', pinyin: 'tóu yūn',   meaning: 'dizzy / lightheaded',        tone: 0, stage: 9, sub: 1 },
  { id: 497, char: '恶心', pinyin: 'ě xīn',     meaning: 'nauseous / disgusted',       tone: 0, stage: 9, sub: 1 },
  { id: 498, char: '受伤', pinyin: 'shòu shāng',meaning: 'to be injured',              tone: 0, stage: 9, sub: 1 },
  { id: 499, char: '流血', pinyin: 'liú xuè',   meaning: 'to bleed',                   tone: 0, stage: 9, sub: 1 },
  { id: 500, char: '过敏', pinyin: 'guò mǐn',   meaning: 'allergy / allergic',         tone: 0, stage: 9, sub: 1 },

  { id: 501, char: '挂号', pinyin: 'guà hào',   meaning: 'to register (at hospital)',  tone: 0, stage: 9, sub: 2 },
  { id: 502, char: '看病', pinyin: 'kàn bìng',  meaning: 'to see a doctor',            tone: 0, stage: 9, sub: 2 },
  { id: 503, char: '医生', pinyin: 'yī shēng',  meaning: 'doctor',                     tone: 0, stage: 9, sub: 2 },
  { id: 504, char: '护士', pinyin: 'hù shi',    meaning: 'nurse',                      tone: 0, stage: 9, sub: 2 },
  { id: 505, char: '打针', pinyin: 'dǎ zhēn',   meaning: 'injection / shot',           tone: 0, stage: 9, sub: 2 },
  { id: 506, char: '住院', pinyin: 'zhù yuàn',  meaning: 'to be hospitalized',         tone: 0, stage: 9, sub: 2 },
  { id: 507, char: '检查', pinyin: 'jiǎn chá',  meaning: 'examination / to check',     tone: 0, stage: 9, sub: 2 },
  { id: 508, char: '验血', pinyin: 'yàn xuè',   meaning: 'blood test',                 tone: 0, stage: 9, sub: 2 },
  { id: 509, char: '手术', pinyin: 'shǒu shù',  meaning: 'surgery / operation',        tone: 0, stage: 9, sub: 2 },
  { id: 510, char: '药', pinyin: 'yào',         meaning: 'medicine',                   tone: 4, stage: 9, sub: 2 },

  { id: 511, char: '运动', pinyin: 'yùn dòng',  meaning: 'exercise / sports',          tone: 0, stage: 9, sub: 3 },
  { id: 512, char: '健康', pinyin: 'jiàn kāng', meaning: 'health / healthy',           tone: 0, stage: 9, sub: 3 },
  { id: 513, char: '锻炼', pinyin: 'duàn liàn', meaning: 'to exercise / work out',     tone: 0, stage: 9, sub: 3 },
  { id: 514, char: '跑步', pinyin: 'pǎo bù',    meaning: 'to run / jog',               tone: 0, stage: 9, sub: 3 },
  { id: 515, char: '游泳', pinyin: 'yóu yǒng',  meaning: 'to swim',                    tone: 0, stage: 9, sub: 3 },
  { id: 516, char: '散步', pinyin: 'sàn bù',    meaning: 'to take a walk',             tone: 0, stage: 9, sub: 3 },
  { id: 517, char: '瑜伽', pinyin: 'yú jiā',    meaning: 'yoga',                       tone: 0, stage: 9, sub: 3 },
  { id: 518, char: '早睡', pinyin: 'zǎo shuì',  meaning: 'to go to bed early',         tone: 0, stage: 9, sub: 3 },
  { id: 519, char: '早起', pinyin: 'zǎo qǐ',    meaning: 'to wake up early',           tone: 0, stage: 9, sub: 3 },
  { id: 520, char: '放松', pinyin: 'fàng sōng', meaning: 'to relax',                   tone: 0, stage: 9, sub: 3 },

  { id: 521, char: '药店', pinyin: 'yào diàn',  meaning: 'pharmacy',                   tone: 0, stage: 9, sub: 4 },
  { id: 522, char: '处方', pinyin: 'chǔ fāng',  meaning: 'prescription',               tone: 0, stage: 9, sub: 4 },
  { id: 523, char: '止痛', pinyin: 'zhǐ tòng',  meaning: 'pain relief',                tone: 0, stage: 9, sub: 4 },
  { id: 524, char: '消炎', pinyin: 'xiāo yán',  meaning: 'anti-inflammatory',          tone: 0, stage: 9, sub: 4 },
  { id: 525, char: '酒精', pinyin: 'jiǔ jīng',  meaning: 'alcohol (rubbing)',          tone: 0, stage: 9, sub: 4 },
  { id: 526, char: '纱布', pinyin: 'shā bù',    meaning: 'gauze',                      tone: 0, stage: 9, sub: 4 },
  { id: 527, char: '创可贴', pinyin: 'chuāng kě tiē', meaning: 'band-aid',             tone: 0, stage: 9, sub: 4 },
  { id: 528, char: '口罩', pinyin: 'kǒu zhào',  meaning: 'face mask',                  tone: 0, stage: 9, sub: 4 },
  { id: 529, char: '体温', pinyin: 'tǐ wēn',    meaning: 'body temperature',           tone: 0, stage: 9, sub: 4 },
  { id: 530, char: '感冒药', pinyin: 'gǎn mào yào', meaning: 'cold medicine',           tone: 0, stage: 9, sub: 4 },

  { id: 531, char: '累', pinyin: 'lèi',         meaning: 'tired',                      tone: 4, stage: 9, sub: 5 },
  { id: 532, char: '开心', pinyin: 'kāi xīn',   meaning: 'happy',                      tone: 0, stage: 9, sub: 5 },
  { id: 533, char: '难过', pinyin: 'nán guò',   meaning: 'sad',                        tone: 0, stage: 9, sub: 5 },
  { id: 534, char: '生气', pinyin: 'shēng qì',  meaning: 'angry',                      tone: 0, stage: 9, sub: 5 },
  { id: 535, char: '担心', pinyin: 'dān xīn',   meaning: 'worried',                    tone: 0, stage: 9, sub: 5 },
  { id: 536, char: '紧张', pinyin: 'jǐn zhāng', meaning: 'nervous',                    tone: 0, stage: 9, sub: 5 },
  { id: 537, char: '无聊', pinyin: 'wú liáo',   meaning: 'bored',                      tone: 0, stage: 9, sub: 5 },
  { id: 538, char: '满意', pinyin: 'mǎn yì',    meaning: 'satisfied',                  tone: 0, stage: 9, sub: 5 },
  { id: 539, char: '骄傲', pinyin: 'jiāo ào',   meaning: 'proud',                      tone: 0, stage: 9, sub: 5 },
  { id: 540, char: '勇敢', pinyin: 'yǒng gǎn',  meaning: 'brave',                      tone: 0, stage: 9, sub: 5 },
];
